/* L01 question bank — review of the physical and data link layers. Owner: Lead. */
(function () {
  'use strict';
  var T = 'l01';
  KIT.bank.add([
    /* ----- Form A: MCQ (5) + Identification (4) ----- */
    { id: 'l01.q001', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L01 p4; L01 p5',
      q: 'Which OSI layer frames the data and moves frames error-free between two end nodes over the physical layer?',
      choices: ['Physical', 'Data link', 'Network', 'Transport'], answer: 1,
      explain: 'The data link layer formats data into frames and enables error-free frame transfer between two end nodes over the physical layer.' },
    { id: 'l01.q002', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L01 p6; L01 p7',
      q: 'According to the slides, a LAN typically connects computers within:',
      choices: ['50 m', '500 m', '5 km', '50 km'], answer: 2,
      explain: 'Slides 6–7: a LAN is a connection of computers typically within 5 km.' },
    { id: 'l01.q003', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L01 p3',
      q: 'In the slides’ TCP/IP model, which layer corresponds to OSI layers 1 and 2?',
      choices: ['Internet', 'Transport', 'Application', 'Network access'], answer: 3,
      explain: 'Network access spans OSI 1–2; Internet = OSI 3; Transport = OSI 4; Application = OSI 5–7.' },
    { id: 'l01.q004', topic: T, pool: 'A', type: 'mcq', diff: 2, ref: 'L01 p17',
      q: 'According to the slides, why is analog transmission needed?',
      choices: ['Analog signals always travel faster than digital signals', 'Bandwidth is limited, so the digital signal is modulated into an analog one', 'Digital signals cannot travel over copper or fiber', 'Analog transmission needs no modulator or demodulator'],
      answer: 1, explain: 'Slide 17: analog transmission is needed when bandwidth is limited; digital signals are modulated into analog signals and transmitted.' },
    { id: 'l01.q005', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L01 p9; L01 p12',
      q: 'Which IEEE standard defines wireless media access control and physical layer specifications (the Wi-Fi family)?',
      choices: ['802.3', '802.5', '802.11', '802.16'], answer: 2,
      explain: '802.11 = wireless MAC and PHY. 802.3 is Ethernet (CSMA/CD), 802.5 token ring, 802.16 wireless local loop.' },
    { id: 'l01.q006', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L01 p10',
      q: 'The term for unused fiber-optic cable.',
      answer: 'Dark fiber', accept: ['dark fibre'], explain: 'Slide 10: “dark fiber” is used for unused fiber-optic cable.' },
    { id: 'l01.q007', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L01 p5',
      q: 'The data link layer service of partitioning data into frames with recognized frame boundaries.',
      answer: 'Framing', accept: ['frame'], explain: 'Framing partitions data into frames and exchanges them over the link.' },
    { id: 'l01.q008', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L01 p14',
      q: 'The OSI layer that translates frames into electrical, optical or electromagnetic signals representing 0s and 1s.',
      answer: 'Physical layer', accept: ['physical', 'layer 1'], explain: 'The physical layer (layer 1) turns frames into signals and specifies cables, connectors and pin signals.' },
    { id: 'l01.q009', topic: T, type: 'id', diff: 1, ref: 'L01 p8',
      q: 'The organization that took responsibility for LAN standards, primarily for the physical and data link layers, using the OSI model as a framework.',
      answer: 'IEEE', accept: ['Institute of Electrical and Electronics Engineers'], explain: 'Slide 8: the IEEE assumed responsibility for setting LAN standards.' },

    /* ----- Form B: MCQ (5) + Identification (4) + Essay (1) ----- */
    { id: 'l01.q010', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L01 p5',
      q: 'Which of these is NOT a service the data link layer provides to the upper layers?',
      choices: ['Framing', 'Flow control', 'Routing packets between networks', 'Error detection'], answer: 2,
      explain: 'Routing packets between networks is the network layer’s job; the data link layer works between adjacent nodes.' },
    { id: 'l01.q011', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L01 p11',
      q: 'SpaceX Starlink satellites are deployed at about what altitude?',
      choices: ['55 km', '550 km', '5,500 km', '35,786 km'], answer: 1,
      explain: 'Slide 11: a global deployment of satellites at 550 km above the earth.' },
    { id: 'l01.q012', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L01 p13',
      q: 'The two styles of media access control named on the slides are:',
      choices: ['ALOHA style and token style', 'TCP and UDP', 'Analog and digital', 'Simplex and duplex'], answer: 0,
      explain: 'Slide 13: ALOHA style and token style.' },
    { id: 'l01.q013', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L01 p15',
      q: 'In the slides’ example of digital transmission, a binary 1 can be represented as:',
      choices: ['−5 V', '0 V', '+5 V', 'a 5 kHz tone'], answer: 2,
      explain: 'Slide 15: a binary 1 can be +5 V and a binary 0 can be 0 V.' },
    { id: 'l01.q014', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L01 p10',
      q: 'Which of these is a WAN technology mentioned on the slides?',
      choices: ['Bluetooth', 'Submarine fiber cable', 'A hub', 'A coaxial patch cord'], answer: 1,
      explain: 'WANs use long-distance fiber such as submarine cable, plus satellite and terrestrial microwave.' },
    { id: 'l01.q015', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L01 p5',
      q: 'The data link layer service that keeps frames in the correct order as they are exchanged.',
      answer: 'Frame sequencing', accept: ['sequencing'], explain: 'Frame sequencing maintains the correct ordering of frames.' },
    { id: 'l01.q016', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L01 p6',
      q: 'The type of network that uses unguided media and can be short or long distance.',
      answer: 'Wireless network', accept: ['wireless'], explain: 'Slide 6: wireless networks — unguided media connection, short or long distance.' },
    { id: 'l01.q017', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L01 p17',
      q: 'The device that converts digital signals into analog signals for transmission (its partner converts them back).',
      answer: 'Modulator', accept: ['modem', 'modulator/demodulator'], explain: 'A modulator converts digital to analog; a demodulator converts analog back to digital.' },
    { id: 'l01.q018', topic: T, pool: 'B', type: 'id', diff: 2, ref: 'L01 p5',
      q: 'The data link layer service that ensures sufficient bandwidth is available and that delays are predictable and guaranteed.',
      answer: 'Quality of service', accept: ['QoS', 'quality of services'], explain: 'Selecting QoS parameters for a transmission.' },
    { id: 'l01.e001', topic: T, pool: 'B', type: 'essay', diff: 2, ref: 'L01 pp4-5; L01 p17',
      q: 'Explain the purpose of the data link layer and describe at least four services it provides to the upper layers. Then explain why digital data is sometimes sent as an analog signal.',
      rubric: [
        { pts: 1, point: 'Purpose: formats data into frames and moves them error-free between two end nodes over the physical layer.' },
        { pts: 2, point: 'At least four services described correctly: framing, frame sequencing, flow control, error detection (sometimes correction), QoS, link provisioning.' },
        { pts: 2, point: 'Analog transmission: needed when bandwidth is limited — the digital signal is modulated onto an analog signal (modulator) and demodulated at the receiver.' }
      ],
      model: '<p>The <b>data link layer</b> regulates and formats the transmission of data from a node onto the network cabling. It dictates data formats, timing and bit sequencing so that ' +
        '<b>frames</b> travel <b>error-free between two end nodes</b> over the physical layer.</p>' +
        '<p>Services: <b>framing</b> (partitioning data into frames with recognized boundaries); <b>frame sequencing</b> (keeping frames in order); <b>flow control</b> (an acceptable flow across the link); ' +
        '<b>error detection</b> (detecting physical-layer errors and notifying, sometimes correcting them); and <b>QoS</b> (ensuring sufficient bandwidth and predictable, guaranteed delays). It also provisions links between adjacent nodes.</p>' +
        '<p>Digital data is sent as an analog signal when the <b>bandwidth is limited</b>: a medium with limited bandwidth cannot pass the digital signal, so a <b>modulator</b> turns it into an analog ' +
        'signal for transmission and a <b>demodulator</b> recovers the digital data at the other end.</p>' },

    /* ----- Diagnostic (3) ----- */
    { id: 'l01.q019', topic: T, pool: 'diag', type: 'mcq', diff: 1, ref: 'L01 p2',
      q: 'On the slides’ OSI table, switches and bridges operate at which layer?',
      choices: ['Physical', 'Data link', 'Network', 'Session'], answer: 1,
      explain: 'They handle frames, so they sit at the data link layer (hubs and repeaters are physical).' },
    { id: 'l01.q020', topic: T, pool: 'diag', type: 'id', diff: 1, ref: 'L01 p9',
      q: 'The IEEE 802 standard that defines CSMA/CD, commonly called Ethernet.',
      answer: '802.3', accept: ['IEEE 802.3'], explain: '802.3 = CSMA/CD Ethernet.' },
    { id: 'l01.q021', topic: T, pool: 'diag', type: 'tf', diff: 1, ref: 'L01 p3',
      q: 'In the slides’ model, the TCP/IP Application layer covers OSI layers 5, 6 and 7.',
      answer: true, explain: 'Application = Session + Presentation + Application of OSI.' },

    /* ----- General ----- */
    { id: 'l01.q022', topic: T, type: 'mcq', diff: 1, ref: 'L01 p5',
      q: 'Which data link service includes error notification when errors are detected but not corrected?',
      choices: ['Framing', 'QoS selection', 'Frame sequencing', 'Error detection'], answer: 3,
      explain: 'Detecting errors in the physical layer includes notification when errors are detected but not corrected.' },
    { id: 'l01.q023', topic: T, type: 'tf', diff: 1, ref: 'L01 p8',
      q: 'Before IEEE standards, organizations often used proprietary networks and were locked into one vendor or technology.',
      answer: true, explain: 'Slide 8: in the early days there were no standards, so organizations were locked into vendors.' },
    { id: 'l01.q024', topic: T, type: 'mcq', diff: 1, ref: 'L01 p10',
      q: 'Which pair are both microwave communication methods for WANs on the slides?',
      choices: ['Satellite and terrestrial microwave links', 'Coax and twisted pair', 'Bluetooth and LTE', 'Hub and repeater'], answer: 0,
      explain: 'Microwave communications: satellites orbiting the earth and terrestrial microwave links.' },
    { id: 'l01.q025', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L01 p12',
      q: 'The coverage unit a wireless network uses to interconnect mobile devices.',
      answer: 'Cell', accept: ['cells'], explain: 'Wireless networks use a “cell” to interconnect mobile devices.' },
    { id: 'l01.q026', topic: T, type: 'mcq', diff: 1, ref: 'L01 p2',
      q: 'On the slides’ OSI table, TCP and UDP belong to which layer?',
      choices: ['Transport', 'Session', 'Network', 'Data link'], answer: 0,
      explain: 'Transport — end-to-end connections.' },
    { id: 'l01.q027', topic: T, type: 'tf', diff: 1, ref: 'L01 p15',
      q: 'An analog signal can carry data by varying its amplitude (voltage), its frequency, or its phase.',
      answer: true, explain: 'Slide 15 lists all three.' },
    { id: 'l01.q028', topic: T, type: 'multi', diff: 1, ref: 'L01 p12',
      q: 'Select <b>all</b> examples of wireless networks given on the slides.',
      choices: ['Bluetooth', 'IEEE 802.11', 'LTE mobile phone network', 'Submarine cable'], answer: [0, 1, 2],
      explain: 'Bluetooth, the IEEE 802.11 series and LTE; submarine cable is a wired WAN medium.' },
    { id: 'l01.q029', topic: T, type: 'id', diff: 2, ref: 'L01 p9',
      q: 'The IEEE 802 standard for the token ring (a logical ring LAN using token passing).',
      answer: '802.5', accept: ['IEEE 802.5'], explain: '802.5 = token ring.' },
    { id: 'l01.q030', topic: T, type: 'mcq', diff: 1, ref: 'L01 p14',
      q: 'Which statement about the physical layer is correct?',
      choices: ['It decides the route a packet takes between networks', 'It encrypts and compresses application data', 'It manages the sessions between user programs', 'It specifies cables, connectors and how bits become signals'],
      answer: 3, explain: 'Slide 14: cable and connector types, the electrical signal on each pin, and how bit values become physical signals.' },
    { id: 'l01.q031', topic: T, type: 'tf', diff: 1, ref: 'L01 p7',
      q: 'LAN computers are normally interconnected using only wireless media.',
      answer: false, fix: 'LAN computers are normally interconnected using copper or fiber media.',
      explain: 'Slide 7: copper or fiber media.' },
    { id: 'l01.q032', topic: T, type: 'id', diff: 1, ref: 'L01 p2',
      q: 'The OSI layer whose role on the slide table is “end-to-end connections”.',
      answer: 'Transport layer', accept: ['transport', 'layer 4'], explain: 'Transport (layer 4): TCP, UDP.' },
    { id: 'l01.q033', topic: T, type: 'mcq', diff: 2, ref: 'L01 p9',
      q: 'Which 802 number defines nothing, because of superstition?',
      choices: ['802.9', '802.12', '802.14', '802.13'], answer: 3,
      explain: '802.13 — IEEE was concerned about the superstitious overtones of “13”.' },
    { id: 'l01.e002', topic: T, pool: 'A', type: 'essay', diff: 2, ref: 'L01 pp2-5; L01 p14',
      q: 'Draw the <b>OSI</b> model and the slides’ <b>TCP/IP</b> model side by side, showing which OSI layers each TCP/IP layer covers. Then explain the job of the two lowest OSI layers.',
      rubric: [
        { pts: 1, point: 'OSI, top to bottom: application, presentation, session, transport, network, data link, physical (7 layers).' },
        { pts: 1, point: 'TCP/IP on the slides: application (= OSI application, presentation and session), transport, internet (= network), network access (= data link and physical).' },
        { pts: 1, point: 'The drawing lines the two stacks up correctly (3 + 1 + 1 + 2 = 7).' },
        { pts: 1, point: 'Physical layer: the physical structure — cables, connectors and how bit values become electrical, optical or electromagnetic signals.' },
        { pts: 1, point: 'Data link layer: formats data into frames and moves them error-free between two end nodes over the physical layer (framing, frame sequencing, flow control, error detection, QoS).' }],
      model: '<figure data-fig="l01.osi"></figure>' +
        '<table class="tbl compact"><thead><tr><th>OSI (7 layers)</th><th>TCP/IP on the slides (4 layers)</th></tr></thead><tbody>' +
        '<tr><td>7 Application · 6 Presentation · 5 Session</td><td>Application</td></tr><tr><td>4 Transport</td><td>Transport</td></tr>' +
        '<tr><td>3 Network</td><td>Internet</td></tr><tr><td>2 Data link · 1 Physical</td><td>Network access</td></tr></tbody></table>' +
        '<p><span class="chip ref">L01 p2</span> <span class="chip ref">L01 p3</span> The <b>physical layer</b> is the physical structure: cable and connector types, the signal on each pin and how bit values become physical signals. <span class="chip ref">L01 p14</span> ' +
        'The <b>data link layer</b> formats data into frames and moves them error-free between two end nodes over the physical layer; its services are framing, frame sequencing, flow control, error detection and QoS. <span class="chip ref">L01 p4</span> <span class="chip ref">L01 p5</span></p>',
      explain: 'Award each rubric point independently; the drawing earns the first three points.' }
  ]);
})();
