/* L02 question bank — Signals, bandwidth, impairments, data-rate limits, performance. Owner: O1.
   pool 'A' = Mock Form A (8 mcq + 5 id + essay e001), 'B' = Mock Form B (8 mcq + 5 id), 'diag' = diagnostic (5, two numeric),
   no pool = general (quick checks, practice, flashcards; the first 8 non-essay items form the topic's quick check).
   Every item has explain + ref; MCQ answer positions are spread evenly; false TF items carry a fix. */
(function () {
  'use strict';
  var T = 'l02';
  KIT.bank.add([
    /* ===== Form A: MCQ (8) — answer positions 2, 3, 1, 0, 2, 0, 3, 1 ===== */
    { id: 'l02.q001', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L02 p5',
      q: 'Which statement about signals is correct?',
      choices: ['Only analog signals can be periodic', 'A nonperiodic signal repeats its pattern in every period',
        'Both analog and digital signals can be periodic or nonperiodic', 'Digital signals can never be periodic'], answer: 2,
      explain: 'A periodic signal repeats a pattern over identical periods; a nonperiodic signal shows no pattern that repeats over time. Both analog and digital signals can be either kind (in practice we commonly use periodic analog and nonperiodic digital signals).' },
    { id: 'l02.q002', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L02 p7',
      q: 'A periodic signal has a period of 4 ms. What is its frequency?',
      choices: ['4 Hz', '4 kHz', '25 Hz', '250 Hz'], answer: 3,
      explain: 'Frequency and period are reciprocals: f = 1/T = 1 / 0.004 s = 250 Hz. (Slide 7: a period of 1/4 s means 4 Hz.)' },
    { id: 'l02.q003', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L02 p8',
      q: 'A sine wave starts at time 0 at its highest point and then falls. In the slide’s convention its phase is:',
      choices: ['0°', '90°', '180°', '270°'], answer: 1,
      explain: 'Slide 8: 0° starts at 0 and rises; 90° starts at the peak; 180° starts at 0 and falls; 270° starts at the trough.' },
    { id: 'l02.q004', topic: T, pool: 'A', type: 'mcq', diff: 2, ref: 'L02 p12; L02 p13',
      q: 'A composite signal is made of sine waves with frequencies <i>f</i>, 3<i>f</i> and 9<i>f</i>, where <i>f</i> = 200 Hz. What is its bandwidth?',
      choices: ['1,600 Hz', '1,800 Hz', '200 Hz', '600 Hz'], answer: 0,
      explain: 'The components are 200, 600 and 1,800 Hz. Bandwidth = highest − lowest = 1,800 − 200 = 1,600 Hz (= 8<i>f</i>). 1,800 Hz is only the highest frequency.' },
    { id: 'l02.q005', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L02 p16; L02 p18',
      q: 'What is <b>baseband</b> transmission?',
      choices: ['Changing a digital signal into an analog signal before sending it', 'Sending analog signals over a bandpass channel',
        'Sending a digital signal over a channel without changing it into an analog signal', 'Sending a signal only over wireless media'], answer: 2,
      explain: 'Baseband sends the digital signal as it is, over a wide-bandwidth (dedicated) medium. Changing it into an analog signal by modulation, which lets us use a bandpass channel, is broadband transmission.' },
    { id: 'l02.q006', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L02 p21; L02 p22',
      q: 'A signal travels through a cable and its power is reduced to one-half. The change is about:',
      choices: ['−3 dB', '−6 dB', '+3 dB', '−0.5 dB'], answer: 0,
      explain: 'dB = 10 log<sub>10</sub>(P<sub>2</sub>/P<sub>1</sub>) = 10 log<sub>10</sub>(0.5) = −3 dB (−3.01). The decibel is negative when the signal is attenuated.' },
    { id: 'l02.q007', topic: T, pool: 'A', type: 'mcq', diff: 2, ref: 'L02 p25; L02 p26',
      q: 'The power of a signal is 2 mW and the power of the noise is 2 µW. What is SNR<sub>dB</sub>?',
      choices: ['3 dB', '20 dB', '25 dB', '30 dB'], answer: 3,
      explain: 'SNR = 2 mW / 2 µW = 2,000 µW / 2 µW = 1,000, so SNR<sub>dB</sub> = 10 log<sub>10</sub>1,000 = 30 dB. Convert both powers to the same unit first.' },
    { id: 'l02.q008', topic: T, pool: 'A', type: 'mcq', diff: 2, ref: 'L02 p29; L02 p30',
      q: 'A noiseless channel has a bandwidth of 3 kHz and uses 4 signal levels. What is the maximum bit rate?',
      choices: ['6 kbps', '12 kbps', '3 kbps', '24 kbps'], answer: 1,
      explain: 'Nyquist: bit rate = 2 × bandwidth × log<sub>2</sub>L = 2 × 3,000 × log<sub>2</sub>4 = 2 × 3,000 × 2 = 12,000 bps.' },

    /* ===== Form A: Identification (5) ===== */
    { id: 'l02.q009', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L02 p20',
      q: 'The loss of some of a signal’s energy as it travels through a medium, in overcoming the resistance of the medium.',
      answer: 'Attenuation', accept: ['signal attenuation'],
      explain: 'Attenuation means a loss of energy; amplifiers are used to compensate for it, and the change in strength is measured in decibels.' },
    { id: 'l02.q010', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L02 p24',
      q: 'The kind of noise caused by the random motion of electrons in a wire.',
      answer: 'Thermal noise', accept: ['thermal'],
      explain: 'Thermal noise is the random motion of electrons in a wire. Induced noise comes from motors and appliances, crosstalk from neighbouring wires, impulse noise from power lines and lightning.' },
    { id: 'l02.q011', topic: T, type: 'id', diff: 1, ref: 'L02 p13',
      q: 'The range of frequencies contained in a composite signal; it is normally the difference between two numbers.',
      answer: 'Bandwidth', accept: [],
      explain: 'Bandwidth = highest frequency − lowest frequency, e.g. 5000 − 1000 = 4000 Hz.' },
    { id: 'l02.q012', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L02 p16',
      q: 'Sending a digital signal over a channel without changing it into an analog signal.',
      answer: 'Baseband transmission', accept: ['baseband'],
      explain: 'Baseband transmission needs a wide-bandwidth medium, a dedicated medium whose bandwidth constitutes only one channel.' },
    { id: 'l02.q013', topic: T, pool: 'diag', type: 'id', diff: 1, ref: 'L02 p34',
      q: 'How long it takes for an entire message to completely arrive at the destination, from the time the first bit is sent out from the source.',
      answer: 'Latency', accept: ['delay', 'latency or delay', 'latency delay'],
      explain: 'Latency (or delay) = propagation time + transmission time + queuing time + processing delay.' },

    /* ===== Form A: Essay ===== */
    { id: 'l02.e001', topic: T, pool: 'A', type: 'essay', diff: 3, ref: 'L02 pp28-33',
      q: 'Compare the <b>Nyquist</b> and <b>Shannon</b> formulas for the data-rate limit of a channel. For each, state the formula, when it applies and what it depends on. ' +
        'Then explain how the two are used together to choose a bit rate and a number of signal levels, using a channel with a 1 MHz bandwidth and an SNR of 63 as your example.',
      rubric: [
        { pts: 1, point: 'Nyquist: for a noiseless channel, bit rate = 2 × bandwidth × log₂L (L = number of signal levels).' },
        { pts: 1, point: 'Shannon: for a noisy channel, capacity = bandwidth × log₂(1 + SNR), with the SNR as a plain ratio (not in dB).' },
        { pts: 1, point: 'Dependencies: Nyquist depends on the bandwidth and the number of levels (more levels raise the rate, but the receiver must be able to tell them apart); Shannon depends on the bandwidth and the SNR only, so the number of levels does not dictate the capacity.' },
        { pts: 1, point: 'Using both: Shannon gives the upper limit for a noisy channel; choose a lower bit rate for better performance, then solve Nyquist for the number of levels.' },
        { pts: 1, point: 'Worked example (slide 33): C = 10⁶ × log₂(1 + 63) = 10⁶ × log₂64 = 6 Mbps; use 4 Mbps → 4 Mbps = 2 × 1 MHz × log₂L → L = 4.' }],
      model: '<p><b>Nyquist</b> applies to a <b>noiseless</b> channel: <i>bit rate = 2 × bandwidth × log<sub>2</sub>L</i>, where L is the number of signal levels. It depends on the bandwidth and on the levels. ' +
        'Increasing the number of levels can increase the bit rate, but the receiver must be able to distinguish the levels.</p>' +
        '<p><b>Shannon</b> applies to a <b>noisy</b> channel: <i>capacity = bandwidth × log<sub>2</sub>(1 + SNR)</i>, with the SNR as a plain ratio (an SNR given in dB must first be converted with SNR = 10<sup>SNR<sub>dB</sub>/10</sup>). ' +
        'It depends only on the bandwidth and the SNR: there is no signal-level term, so the number of levels does not dictate the capacity of the channel.</p>' +
        '<p><b>Used together:</b> Shannon tells us the upper limit of the bit rate that the noisy channel can ever carry. We then pick a bit rate at or below that limit (a lower rate gives better performance) and use Nyquist, solved for L, to find how many signal levels that rate needs.</p>' +
        '<p><b>Example (slide 33):</b> B = 1 MHz and SNR = 63. Shannon: C = 10<sup>6</sup> × log<sub>2</sub>(1 + 63) = 10<sup>6</sup> × log<sub>2</sub>64 = 6 Mbps, the upper limit. We choose 4 Mbps. Nyquist: 4 Mbps = 2 × 1 MHz × log<sub>2</sub>L, so log<sub>2</sub>L = 2 and L = 4 signal levels.</p>',
      explain: 'Award each rubric point independently; accept an equivalent worked example with correct arithmetic.' },

    /* ===== Form B: MCQ (8) — answer positions 0, 2, 3, 1, 3, 0, 1, 2 ===== */
    { id: 'l02.q014', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L02 p9; L02 p10',
      q: 'A signal of 6 MHz travels in free space (c = 3×10<sup>8</sup> m/s). What is its wavelength?',
      choices: ['50 m', '5 m', '0.02 m', '18 m'], answer: 0,
      explain: 'λ = c / f = (3×10<sup>8</sup> m/s) / (6×10<sup>6</sup> Hz) = 50 m.' },
    { id: 'l02.q015', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L02 p14',
      q: 'A digital signal has 16 levels. How many bits does each level carry?',
      choices: ['16 bits', '8 bits', '4 bits', '2 bits'], answer: 2,
      explain: 'A signal with L levels needs log<sub>2</sub>L bits for each level: log<sub>2</sub>16 = 4 bits.' },
    { id: 'l02.q016', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L02 p23',
      q: 'Why can a composite signal be <b>distorted</b> on its way through a medium?',
      choices: ['The noise power is larger than the signal power', 'An amplifier adds the same gain to every frequency',
        'It loses some of its energy in overcoming the resistance of the medium', 'Its frequency components travel at different propagation speeds and arrive at different times'], answer: 3,
      explain: 'Distortion changes the signal’s form or shape because the components of a composite signal arrive at different times. Loss of energy is attenuation; unwanted signals are noise.' },
    { id: 'l02.q017', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L02 p24',
      q: 'During a phone call you faintly hear a conversation from a neighbouring wire. This is:',
      choices: ['thermal noise', 'crosstalk', 'impulse noise', 'induced noise'], answer: 1,
      explain: 'Crosstalk is signals jumping from one wire to another, normally between adjacent wires.' },
    { id: 'l02.q018', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L02 p31',
      q: 'According to Shannon, the capacity of a channel depends on:',
      choices: ['the bandwidth and the number of signal levels', 'the number of signal levels and the SNR',
        'the propagation speed and the distance', 'the bandwidth and the signal-to-noise ratio'], answer: 3,
      explain: 'C = B × log<sub>2</sub>(1 + SNR). There is no signal-level term: the levels of the signal do not dictate the capacity of the channel.' },
    { id: 'l02.q019', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L02 p31; L02 p33',
      q: 'A noisy channel has a bandwidth of 2 MHz and an SNR of 15. What is its Shannon capacity?',
      choices: ['8 Mbps', '30 Mbps', '4 Mbps', '2 Mbps'], answer: 0,
      explain: 'C = B log<sub>2</sub>(1 + SNR) = 2 MHz × log<sub>2</sub>16 = 2 MHz × 4 = 8 Mbps.' },
    { id: 'l02.q020', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L02 p34',
      q: 'A link has a bandwidth of 10 Mbps. What can be said about the throughput through it?',
      choices: ['It is always equal to 10 Mbps', 'It is always less than 10 Mbps', 'It can be greater than 10 Mbps', 'It is unrelated to the bandwidth'], answer: 1,
      explain: 'Slide 34: a link may have a bandwidth of B bps, but we can only send T bps through it, with T always less than B.' },
    { id: 'l02.q021', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L02 p35; L02 p37',
      q: 'What is the propagation time over a 3,000 km link if signals travel at 2×10<sup>8</sup> m/s?',
      choices: ['1.5 ms', '6 ms', '15 ms', '150 ms'], answer: 2,
      explain: 'Propagation time = distance / propagation speed = (3,000 × 1,000 m) / (2×10<sup>8</sup> m/s) = 0.015 s = 15 ms.' },

    /* ===== Form B: Identification (5) ===== */
    { id: 'l02.q022', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L02 p23',
      q: 'A change in the form or shape of a composite signal because its frequency components propagate at different speeds.',
      answer: 'Distortion', accept: ['signal distortion'],
      explain: 'Distortion means the signal changes its form or shape; the components of a composite signal arrive at different times.' },
    { id: 'l02.q023', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L02 p24',
      q: 'The kind of noise in which signals jump from one wire to another, normally between adjacent wires.',
      answer: 'Crosstalk', accept: ['cross talk'],
      explain: 'Crosstalk is signals jumping from one wire to another.' },
    { id: 'l02.q024', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L02 p12',
      q: 'The main frequency of a composite signal (in the slide example the other sine waves have 3 and 9 times this frequency).',
      answer: 'Fundamental frequency', accept: ['fundamental'],
      explain: 'The main frequency of a composite signal is normally called the fundamental frequency (f; the others are 3f and 9f).' },
    { id: 'l02.q025', topic: T, type: 'id', diff: 1, ref: 'L02 p18',
      q: 'A channel whose bandwidth does not start from zero; modulation lets a digital signal use it.',
      answer: 'Bandpass channel', accept: ['bandpass'],
      explain: 'Modulation allows us to use a bandpass channel, a channel with a bandwidth that does not start from zero (broadband transmission).' },
    { id: 'l02.q026', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L02 p34',
      q: 'The difference in delay (latency) from one packet to another.',
      answer: 'Jitter', accept: ['delay jitter'],
      explain: 'Jitter is the difference in delay or latency per packet.' },

    /* ===== Diagnostic (5): two numeric, one MCQ, one identification, one true/false ===== */
    { id: 'l02.q027', topic: T, pool: 'diag', type: 'num', diff: 2, ref: 'L02 p29; L02 p30',
      q: 'A noiseless channel has a bandwidth of 4 kHz and uses 8 signal levels. What is the maximum bit rate?',
      num: { value: 24000, tol: 0.01, rel: true, unit: 'bps' },
      explain: 'Nyquist: 2 × 4,000 × log<sub>2</sub>8 = 2 × 4,000 × 3 = 24,000 bps.' },
    { id: 'l02.q028', topic: T, pool: 'diag', type: 'num', diff: 2, ref: 'L02 p21',
      q: 'An amplifier multiplies a signal’s power by 100. What is its gain in decibels?',
      num: { value: 20, tol: 0.1, rel: false, unit: 'dB' },
      explain: 'dB = 10 log<sub>10</sub>(P<sub>2</sub>/P<sub>1</sub>) = 10 log<sub>10</sub>100 = 10 × 2 = +20 dB (positive, because the signal is amplified).' },
    { id: 'l02.q029', topic: T, pool: 'diag', type: 'mcq', diff: 1, ref: 'L02 p28; L02 p31',
      q: 'Which formula gives the maximum bit rate of a <b>noisy</b> channel?',
      choices: ['bit rate = 2 × B × log₂L', 'C = B × log₂(1 + SNR)', 'f = 1/T', 'dB = 10 log₁₀(P₂/P₁)'], answer: 1,
      explain: 'A noisy channel needs the Shannon capacity. Nyquist (2 × B × log<sub>2</sub>L) is for a noiseless channel.' },
    { id: 'l02.q030', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L02 p20',
      q: 'The unit engineers use to show that a signal has lost or gained strength.',
      answer: 'Decibel', accept: ['dB', 'deciBel', 'db'],
      explain: 'The decibel (dB) measures the relative strengths of two signals, or of one signal at two points: negative if attenuated, positive if amplified.' },
    { id: 'l02.q031', topic: T, pool: 'diag', type: 'tf', diff: 1, ref: 'L02 p38',
      q: 'A digital signal can be viewed as a composite analog signal with an infinite bandwidth.',
      answer: true, explain: 'This is on the summary slide: a digital signal is a composite analog signal with an infinite bandwidth.' },

    /* ===== General: quick checks, practice, flashcards (the first 8 below form the quick check) ===== */
    { id: 'l02.q032', topic: T, type: 'mcq', diff: 2, ref: 'L02 p22',
      q: 'On slide 22 the power is “reduced to one-half”. Which equation describes that?',
      choices: ['P<sub>2</sub> = 0.5 × P<sub>1</sub>', 'P<sub>2</sub> = P<sub>1</sub>', 'P<sub>2</sub> = 2 × P<sub>1</sub>', 'P<sub>2</sub> = P<sub>1</sub> − 0.5'], answer: 0,
      explain: 'Half of P<sub>1</sub> is P<sub>2</sub> = 0.5 P<sub>1</sub>, which gives 10 log<sub>10</sub>0.5 = −3 dB. (The slide text prints “P2 = P1” by mistake — the ½ is missing.)' },
    { id: 'l02.q033', topic: T, type: 'tf', diff: 1, ref: 'L02 p14',
      q: 'A digital signal can have more than two levels.',
      answer: true, explain: 'Slide 14: a digital signal can have more than two levels; with L levels, each level needs log<sub>2</sub>L bits (the 4-level example carries 2 bits per level).' },
    { id: 'l02.q034', topic: T, type: 'num', diff: 1, ref: 'L02 p9; L02 p10',
      q: 'Green light has a frequency of 5×10<sup>14</sup> Hz. What is its wavelength in free space (c = 3×10<sup>8</sup> m/s)?',
      num: { value: 6e-7, tol: 0.01, rel: true, unit: 'm' },
      explain: 'λ = c / f = (3×10<sup>8</sup>) / (5×10<sup>14</sup>) = 6×10<sup>−7</sup> m = 0.6 µm.' },
    { id: 'l02.q035', topic: T, type: 'multi', diff: 2, ref: 'L02 p24',
      q: 'Select <b>all</b> the types of noise named in the lecture.',
      choices: ['Thermal noise', 'Induced noise', 'Attenuation', 'Crosstalk', 'Impulse noise'], answer: [0, 1, 3, 4],
      explain: 'The four noise types are thermal, induced, crosstalk and impulse noise. Attenuation is a different impairment (a loss of energy), as is distortion.' },
    { id: 'l02.q036', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L02 p11',
      q: 'The French mathematician who showed that a composite signal is a combination of simple sine waves with different frequencies, amplitudes and phases.',
      answer: 'Fourier', accept: ['Jean-Baptiste Fourier', 'Joseph Fourier', 'Jean-Baptiste Joseph Fourier'],
      explain: 'Fourier showed that any composite signal is a sum of simple sine waves. (The slide says “early 1900s”; his work dates from the early 1800s.)' },
    { id: 'l02.q037', topic: T, type: 'mcq', diff: 1, ref: 'L02 p27',
      q: '1000 kbps equals:',
      choices: ['1 Gbps', '100 kbps', '1 Mbps', '10 Mbps'], answer: 2,
      explain: 'The slide’s data-rate title says it: 1000 kbps = 1 Mbps (decimal prefixes, a factor of 1000 each).' },
    { id: 'l02.q038', topic: T, type: 'num', diff: 2, ref: 'L02 p25; L02 p26',
      q: 'A channel has an SNR of 1,000. Express it in decibels.',
      num: { value: 30, tol: 0.1, rel: false, unit: 'dB' },
      explain: 'SNR<sub>dB</sub> = 10 log<sub>10</sub>SNR = 10 log<sub>10</sub>1,000 = 10 × 3 = 30 dB.' },
    { id: 'l02.q039', topic: T, type: 'tf', diff: 2, ref: 'L02 p31',
      q: 'In Shannon’s formula, using more signal levels increases the capacity of the channel.',
      answer: false, fix: 'C = B × log₂(1 + SNR) has no signal-level term: the levels of the signal do not dictate the capacity of the channel.',
      explain: 'Capacity depends on the bandwidth and the SNR. (More levels raise the Nyquist bit rate of a noiseless channel, but never beyond the Shannon limit of a noisy one.)' },
    { id: 'l02.q040', topic: T, type: 'num', diff: 2, ref: 'L02 p13; L02 p32',
      q: 'A telephone line is assigned the frequencies from 300 Hz to 3300 Hz for data. What is its bandwidth?',
      num: { value: 3000, tol: 0.01, rel: true, unit: 'Hz' },
      explain: 'Bandwidth = highest − lowest = 3300 − 300 = 3000 Hz (the slide-32 telephone line).' },
    { id: 'l02.q041', topic: T, type: 'num', diff: 2, ref: 'L02 p31',
      q: 'A channel with a bandwidth of 4 kHz has an SNR of 15 (a plain ratio). What is its Shannon capacity?',
      num: { value: 16000, tol: 0.01, rel: true, unit: 'bps' },
      explain: 'C = 4,000 × log<sub>2</sub>(1 + 15) = 4,000 × log<sub>2</sub>16 = 4,000 × 4 = 16,000 bps.' },
    { id: 'l02.q042', topic: T, type: 'tf', diff: 2, ref: 'L02 p25; L02 p31',
      q: 'Shannon’s formula takes the SNR in decibels.',
      answer: false, fix: 'It takes the plain SNR ratio. Convert first: SNR = 10^(SNR_dB / 10).',
      explain: 'Plugging a dB value into log₂(1 + SNR) gives a wrong capacity; always convert SNR<sub>dB</sub> back to the ratio.' },
    { id: 'l02.q043', topic: T, type: 'tf', diff: 1, ref: 'L02 p21',
      q: 'The decibel value is negative when a signal is attenuated.',
      answer: true, explain: 'Slide 21: the decibel is negative if a signal is attenuated and positive if it is amplified.' },
    { id: 'l02.q044', topic: T, type: 'tf', diff: 1, ref: 'L02 p16; L02 p18',
      q: 'In baseband transmission the digital signal is first changed into an analog signal.',
      answer: false, fix: 'Changing the digital signal into an analog signal is broadband transmission; baseband sends the digital signal without changing it.',
      explain: 'Baseband = no conversion (wide-bandwidth medium). Broadband = modulation, which allows a bandpass channel.' },
    { id: 'l02.q045', topic: T, type: 'num', diff: 2, ref: 'L02 p35; L02 p37',
      q: 'What is the propagation time of a signal over 600 km if it travels at 2×10<sup>8</sup> m/s?',
      num: { value: 0.003, tol: 0.01, rel: true, unit: 's' },
      explain: 'Propagation time = distance / speed = (600 × 1000 m) / (2×10<sup>8</sup> m/s) = 0.003 s = 3 ms.' },
    { id: 'l02.q046', topic: T, type: 'num', diff: 2, ref: 'L02 p35; L02 p37',
      q: 'What is the transmission time of a 10,000-byte message on a 1 Mbps link?',
      num: { value: 0.08, tol: 0.01, rel: true, unit: 's' },
      explain: 'Message size = 10,000 × 8 = 80,000 bits; transmission time = size / bandwidth = 80,000 / 10<sup>6</sup> = 0.08 s = 80 ms.' },
    { id: 'l02.q047', topic: T, type: 'num', diff: 2, ref: 'L02 p29',
      q: 'A noiseless channel must carry 24 kbps using 8 signal levels. What minimum bandwidth does it need?',
      num: { value: 4000, tol: 0.01, rel: true, unit: 'Hz' },
      explain: 'Nyquist: bandwidth = bit rate / (2 × log<sub>2</sub>L) = 24,000 / (2 × 3) = 4,000 Hz.' },
    { id: 'l02.q048', topic: T, type: 'multi', diff: 2, ref: 'L02 p29; L02 p31',
      q: 'Which quantities appear in <b>Nyquist’s</b> formula for the bit rate of a noiseless channel?',
      choices: ['Bandwidth', 'Number of signal levels', 'Signal-to-noise ratio', 'Propagation speed'], answer: [0, 1],
      explain: 'Bit rate = 2 × bandwidth × log<sub>2</sub>L uses the bandwidth and the levels. The SNR belongs to Shannon’s formula; propagation speed belongs to latency.' },
    { id: 'l02.q049', topic: T, type: 'mcq', diff: 2, ref: 'L02 p18',
      q: 'Modulation lets a digital signal use which kind of channel?',
      choices: ['A channel that must start from 0 Hz', 'A noiseless channel', 'A dedicated one-channel baseband cable', 'A bandpass channel (bandwidth not starting from zero)'], answer: 3,
      explain: 'Broadband transmission changes the digital signal into an analog one; modulation allows us to use a bandpass channel.' },
    { id: 'l02.q050', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L02 p34',
      q: 'A measure of how fast we can actually send data through a network (always less than the link’s bandwidth).',
      answer: 'Throughput', accept: [],
      explain: 'A link may have a bandwidth of B bps, but we can only send T bps through it, with T always less than B.' },
    { id: 'l02.q051', topic: T, type: 'mcq', diff: 3, ref: 'L02 p17',
      q: 'To approximate a digital signal of bit rate N with harmonics at N/2, 3N/2 and 5N/2, a low-pass channel needs a bandwidth of about:',
      choices: ['N/2', '3N/2', '5N/2', '9N/2'], answer: 2,
      explain: 'The highest harmonic used sets the bandwidth: the first harmonic alone needs N/2; adding 3N/2 and 5N/2 needs 5N/2. A better approximation needs more bandwidth.' },
    { id: 'l02.q052', topic: T, type: 'num', diff: 2, beyond: true, ref: 'L02 p21; Forouzan',
      q: 'A signal passes through a cable section with a 10 dB loss, an amplifier with a 30 dB gain, and another cable section with a 10 dB loss. What is the net change in decibels?',
      num: { value: 10, tol: 0.1, rel: false, unit: 'dB' },
      explain: 'Decibels of cascaded stages add (textbook rule): −10 + 30 − 10 = +10 dB, a net gain.' },
    { id: 'l02.q053', topic: T, type: 'num', diff: 2, beyond: true, ref: 'L02 p14; Forouzan',
      q: 'Signals travel at 2×10<sup>8</sup> m/s along a link that sends 1 Mbps. How long, in metres, is one bit on the medium?',
      num: { value: 200, tol: 0.01, rel: true, unit: 'm' },
      explain: 'Bit duration = 1 / 10<sup>6</sup> s = 1 µs; bit length = propagation speed × bit duration = 2×10<sup>8</sup> × 10<sup>−6</sup> = 200 m (textbook formula; slide 14 defines bit length only in words).' },

    /* ===== General essay (practice only; never in a quick check) ===== */
    { id: 'l02.e002', topic: T, pool: 'B', type: 'essay', diff: 2, ref: 'L02 pp19-26',
      q: 'Describe the three transmission impairments named in the lecture: <b>attenuation</b>, <b>distortion</b> and <b>noise</b>. For each, draw (or describe) what it does to a signal and say what causes it; ' +
        'then explain how losses, gains and noise are measured.',
      rubric: [
        { pts: 1, point: 'Attenuation: loss of energy as the signal overcomes the resistance of the medium; amplifiers compensate.' },
        { pts: 1, point: 'Distortion: the signal changes its form or shape; the components of a composite signal arrive at different times because each frequency propagates at a different speed.' },
        { pts: 1, point: 'Noise: unwanted signals that corrupt the signal at the receiving end — thermal (random motion of electrons), induced (motors and appliances), crosstalk (adjacent wires), impulse (spikes from power lines, lightning).' },
        { pts: 1, point: 'Decibel: dB = 10 log₁₀(P₂/P₁), negative for attenuation and positive for amplification; e.g. half the power is −3 dB.' },
        { pts: 1, point: 'SNR = average signal power / average noise power; SNR_dB = 10 log₁₀ SNR; high SNR means a less corrupted signal (e.g. 10 mW over 1 µW → 10,000 → 40 dB).' }],
      model: '<p><b>Attenuation</b> is a loss of energy: a signal, simple or composite, loses some of its energy in overcoming the resistance of the medium. Amplifiers are used to compensate. ' +
        '<b>Distortion</b> means the signal changes its form or shape. In a composite signal each frequency component propagates at its own speed, so the components arrive at different times and the received shape no longer matches the one sent. ' +
        '<b>Noise</b> corrupts the signal at the receiving end. <i>Thermal</i> noise is the random motion of electrons in a wire; <i>induced</i> noise comes from motors and appliances that act as sending antennas while the medium acts as a receiving antenna; ' +
        '<i>crosstalk</i> is signals jumping from one wire to another, normally adjacent; <i>impulse</i> noise is a spike from power lines, lightning and the like.</p>' +
        '<figure data-fig="l02.impairments"></figure>' +
        '<p>The <b>decibel</b> measures the relative strength of two signals or of one signal at two points: dB = 10 log<sub>10</sub>(P<sub>2</sub>/P<sub>1</sub>). It is negative when the signal is attenuated and positive when it is amplified; ' +
        'halving the power gives 10 log<sub>10</sub>0.5 = −3 dB. The <b>SNR</b> is the ratio of what is wanted to what is not wanted: SNR = average signal power / average noise power, and SNR<sub>dB</sub> = 10 log<sub>10</sub>SNR. ' +
        'A high SNR means the signal is less corrupted by noise. Example: 10 mW of signal over 1 µW of noise gives SNR = 10,000 and SNR<sub>dB</sub> = 40 dB.</p>',
      explain: 'Award each rubric point independently.' }
  ]);
})();
