/* L03a question bank — line coding, block coding, scrambling (L03 slides 1–61). Owner: O2.
   pool 'A' = Mock Form A (8 mcq + 5 id + essay), 'B' = Mock Form B (8 mcq + 5 id), 'diag' = diagnostic (5), no pool = general (quick checks, practice, flashcards).
   MCQ answer positions are spread over A–D; every item has explain + ref; false TF items carry a fix.
   Where the slides contradict themselves (NRZ-L p22 vs p23, Manchester p5 vs p29, the 2B1Q r on p38, the AMI row on p46) the exam-pool items avoid the contradiction;
   the general items teach it. */
(function () {
  'use strict';
  var T = 'l03a';
  KIT.bank.add([
    /* ===================== Form A: MCQ (8) ===================== */
    { id: 'l03a.q001', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L03 p11',
      q: 'What is <b>baseline wandering</b>?',
      choices: ['A slow change in the sender’s clock frequency', 'A drift of the receiver’s running-average baseline, caused by a long string of 0s or 1s',
        'The delay between the first and the last bit of a block', 'Noise that the channel adds to the signal'],
      answer: 1,
      explain: 'In decoding, the receiver keeps a running average of the received signal power — the baseline. A long run of the same level drags that average away, so the receiver has trouble telling 0s from 1s (slide 11).' },
    { id: 'l03a.q002', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L03 p30; L03 p46',
      q: 'Compared with NRZ, the <b>minimum bandwidth</b> of Manchester coding is:',
      choices: ['Half as much', 'The same', 'One and a half times as much', 'Twice as much'],
      answer: 3,
      explain: 'Manchester sends two signal elements for every bit (r = 1/2), so its average signal rate is N while NRZ needs only N/2 — twice the bandwidth (slide 30; the table on slide 46 lists B = N against N/2).' },
    { id: 'l03a.q003', topic: T, pool: 'A', type: 'mcq', diff: 2, ref: 'L03 p25',
      q: 'A system uses NRZ-I to send data at 2 Mbps. What is the minimum bandwidth (average case)?',
      choices: ['1 MHz', '500 kHz', '2 MHz', '4 MHz'],
      answer: 0,
      explain: 'NRZ-I has r = 1 and the average case uses c = 1/2: S = c × N × 1/r = ½ × 2 Mbps × 1 = 1 Mbaud. The minimum bandwidth equals the signal rate, B<sub>min</sub> = S = 1 MHz (Example 3 on slide 25 does the same with 1 Mbps).' },
    { id: 'l03a.q004', topic: T, pool: 'A', type: 'mcq', diff: 2, ref: 'L03 p60',
      q: 'HDB3 substitutes four zeros with <b>000V</b> when the number of nonzero pulses since the last substitution is odd. What does it use when that number is <b>even</b>?',
      choices: ['000V', '000VB0VB', 'B00V', '0000 (no substitution)'],
      answer: 2,
      explain: 'Slide 60: even → B00V, odd → 000V — in both cases the total number of nonzero pulses becomes even. 000VB0VB is the B8ZS pattern for eight zeros.' },
    { id: 'l03a.q005', topic: T, pool: 'A', type: 'mcq', diff: 2, ref: 'L03 p48; L03 p54',
      q: 'Data at 8 Mbps is block-coded with 4B/5B before line coding. What is the bit rate on the line after block coding?',
      choices: ['6.4 Mbps', '8 Mbps', '16 Mbps', '10 Mbps'],
      answer: 3,
      explain: '4B/5B replaces every 4 bits by 5, so N′ = N × 5/4 = 8 × 5/4 = 10 Mbps (slide 54: 1 Mbps becomes 1.25 Mbps). 6.4 Mbps would be N × 4/5 — the wrong direction.' },
    { id: 'l03a.q006', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L03 p26; L03 p28',
      q: 'Which line code has a level transition in the middle of <b>every</b> bit and uses only <b>two</b> voltage levels?',
      choices: ['RZ', 'Manchester', 'AMI', 'NRZ-I'],
      answer: 1,
      explain: 'Manchester (and differential Manchester) always change level in the middle of the bit using only +V and −V (slide 28). RZ also has a mid-bit transition but needs three levels (+, 0, −); AMI has three levels and no mid-bit transition; NRZ-I only changes level for a 1.' },
    { id: 'l03a.q007', topic: T, pool: 'A', type: 'mcq', diff: 2, ref: 'L03 p35; L03 p36',
      q: 'In an mBnL code, 2<sup>m</sup> ≤ L<sup>n</sup> must hold. Which of these codes is <b>not</b> valid?',
      choices: ['2B1Q', '8B6T', '3B1Q', '4B3T'],
      answer: 2,
      explain: '3B1Q needs 2³ = 8 data patterns but only 4¹ = 4 signal patterns exist. The others pass: 2B1Q 4 ≤ 4, 8B6T 256 ≤ 729, 4B3T 16 ≤ 27 (slide 36).' },
    { id: 'l03a.q008', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L03 p33',
      q: 'Which description of <b>AMI</b> matches the slide notes?',
      choices: ['No DC component or baseline wandering, but no self-synchronization during a long run of 0s', 'A DC component, but good self-synchronization',
        'Self-synchronization and error detection, but a DC component', 'No DC component and a transition in the middle of every bit'],
      answer: 0,
      explain: 'Slide 33: AMI has no DC component or baseline wandering, but a long run of 0s gives no signal transitions, so it cannot self-synchronize; it has no error detection. (The summary table on slide 46 marks AMI “DC”, which contradicts slide 33.)' },

    /* ===================== Form A: Identification (5) ===================== */
    { id: 'l03a.q009', topic: T, type: 'id', diff: 1, ref: 'L03 p6',
      q: 'The unit in which the <b>signal rate</b> — the number of signal elements sent per second — is measured.',
      answer: 'Baud', accept: ['bauds', 'baud rate', 'bd'],
      explain: 'The data rate is measured in bps (bits per second); the signal rate, also called the modulation rate, is measured in bauds (slide 6).' },
    { id: 'l03a.q010', topic: T, type: 'id', diff: 2, ref: 'L03 p28; L03 p29',
      q: 'The biphase code that combines NRZ-I and RZ: every bit has a transition in the middle, and a 0 also has a transition at the start of the bit.',
      answer: 'Differential Manchester', accept: ['differential manchester encoding', 'differential manchester code', 'differential manchester coding', 'differential manchester scheme', 'diff manchester', 'diff manchester coding', 'diff manchester encoding'],
      explain: 'Differential Manchester always changes level in the middle of the bit; whether the level changes at the start of the bit carries the data (0 = change, 1 = no change; slide 29).' },
    { id: 'l03a.q011', topic: T, pool: 'A', type: 'id', diff: 2, ref: 'L03 p59',
      q: 'The scrambling technique that replaces eight consecutive zeros with 000VB0VB.',
      answer: 'B8ZS', accept: ['bipolar with 8-zero substitution', 'b8zs scrambling'],
      explain: 'B8ZS: V = violation, B = bipolar pulse (slide 59). HDB3 is the four-zero counterpart (000V or B00V, slides 60–61).' },
    { id: 'l03a.q012', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L03 p48',
      q: 'The third step of block coding, after division and substitution, in which the n-bit groups are joined back into one stream.',
      answer: 'Combination', accept: ['combining', 'combine'],
      explain: 'Block coding is done in three steps: division, substitution and combination (slides 48–49).' },
    { id: 'l03a.q013', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L03 p26',
      q: 'The polar scheme that uses three voltage values (+, 0, −) and has a transition in the middle of every symbol, from high or low to zero.',
      answer: 'RZ', accept: ['Return to Zero', 'Return-to-Zero', 'polar RZ', 'RZ scheme', 'RZ coding', 'return to zero scheme', 'return to zero coding'],
      explain: 'RZ (Return to Zero): a 1 is +V then 0 V, a 0 is −V then 0 V. It has two transitions per symbol, so it needs a wider bandwidth, but no DC component and it self-synchronizes (slides 26–27).' },

    /* ===================== Form A: Essay ===================== */
    { id: 'l03a.e001', topic: T, pool: 'A', type: 'essay', diff: 3, ref: 'L03 pp11-13; L03 p24; L03 p30; L03 p33',
      q: 'Compare <b>NRZ-L, NRZ-I, Manchester and AMI</b> for three properties: <b>baseline wandering</b>, <b>DC component</b> and <b>self-synchronization</b>. For each code, say whether it has the problem and explain <i>why</i>. You may draw a short bit stream (for example a 1 followed by a long run of 0s) in each code to support your answer.',
      rubric: [
        { pts: 1, point: 'Defines the properties: baseline wandering = the receiver’s running average (the baseline) drifts during long runs of one level; DC component = a constant level for long periods adds low-frequency content that bandpass channels may not pass; self-synchronization = the signal itself has enough transitions for the receiver’s clock to stay in step with the sender’s.' },
        { pts: 1, point: 'NRZ-L: a long run of 0s or 1s is a constant level, so it has baseline wandering and a DC component (worse than NRZ-I) and no self-synchronization.' },
        { pts: 1, point: 'NRZ-I: a 1 always inverts the level, so runs of 1s keep transitions, but a long run of 0s is a constant level — DC component and baseline wandering remain (less than NRZ-L) and there is no self-synchronization for long 0s.' },
        { pts: 1, point: 'Manchester: a transition in the middle of every bit gives self-synchronization, and the average level is zero, so there is no DC component or baseline wandering — at the price of two signal elements per bit (S = N, twice the bandwidth of NRZ).' },
        { pts: 1, point: 'AMI: the 1s alternate in polarity, so there is no DC component or baseline wandering, but a long run of 0s (0 V) has no transitions, so no self-synchronization (the remedy is scrambling: B8ZS / HDB3).' }],
      model: '<p>All three properties come from <b>how long the signal stays at one level</b>.</p>' +
        '<figure data-fig="l03a.linecode" data-scheme="nrzl,nrzi,manchester,ami" data-bits="10000000" data-caption="A 1 then seven 0s: NRZ-L, NRZ-I and AMI stay flat through the 0s; Manchester still changes in the middle of every bit."></figure>' +
        '<ul><li><b>Baseline wandering</b> — the receiver decodes against a running average of the received signal power (the baseline). A long string of 0s or 1s drags that average away, so levels become hard to tell apart. <span class="chip ref">L03 p11</span></li>' +
        '<li><b>DC component</b> — when the voltage stays constant for long periods the low frequencies of the signal grow; most channels are bandpass and may not pass them, so the DC component has to be avoided. <span class="chip ref">L03 p12</span></li>' +
        '<li><b>Self-synchronization</b> — sender and receiver clocks must have the same bit interval; if the signal carries enough transitions, the receiver can re-align its clock to them. <span class="chip ref">L03 p13</span></li></ul>' +
        '<table class="tbl compact"><thead><tr><th>Code</th><th>Baseline wandering / DC</th><th>Self-synchronization</th><th>Why</th></tr></thead><tbody>' +
        '<tr><td><b>NRZ-L</b></td><td>Yes — worse than NRZ-I</td><td>No</td><td>The level itself is the bit, so a long run of 0s or 1s is a flat line. <span class="chip ref">L03 p24</span></td></tr>' +
        '<tr><td><b>NRZ-I</b></td><td>Yes — less severe</td><td>No (for long 0s)</td><td>A 1 inverts the level, so 1s keep producing transitions; a run of 0s is a flat line. <span class="chip ref">L03 p24</span> <span class="chip ref">L03 p46</span></td></tr>' +
        '<tr><td><b>Manchester</b></td><td>No</td><td>Yes</td><td>Every bit has a mid-bit transition (high→low or low→high), so the average is zero and the receiver sees a transition every bit. Cost: two signal elements per bit (S = N, twice NRZ’s bandwidth). <span class="chip ref">L03 p30</span></td></tr>' +
        '<tr><td><b>AMI</b></td><td>No</td><td>No (for long 0s)</td><td>The 1s alternate +V / −V, so the positive and negative pulses cancel; but 0s are 0 V, and a long run of 0s has no transitions. <span class="chip ref">L03 p33</span></td></tr></tbody></table>' +
        '<p>Remedy for AMI: scrambling (B8ZS or HDB3) replaces long zero runs with violation pulses. <span class="chip ref">L03 p57</span> Note: the summary table on slide 46 marks AMI “DC”, which contradicts slide 33 — AMI has no DC component.</p>',
      explain: 'Tie every property to long runs of one level: NRZ-L/NRZ-I have them (DC, baseline wandering, no sync); Manchester forces a mid-bit transition (self-sync, no DC) at twice the bandwidth; AMI cancels DC by alternating 1s but has no transitions in 0-runs.' },

    /* ===================== Form B: MCQ (8) ===================== */
    { id: 'l03a.q014', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L03 p12',
      q: 'Why is a <b>DC component</b> a problem for line coding?',
      choices: ['It makes the baud rate higher than the bit rate', 'It needs an extra wire to carry the clock',
        'Most channels are bandpass and may not support the low frequencies that a constant level creates', 'It makes every bit have a mid-bit transition'],
      answer: 2,
      explain: 'When the voltage stays constant for long periods, the low-frequency content of the signal increases. Most channels are bandpass and may not pass low frequencies, so the DC component has to be removed (slide 12).' },
    { id: 'l03a.q015', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L03 p38; L03 p46',
      q: 'A data stream of rate N is sent with <b>2B1Q</b>. What is the average signal (baud) rate?',
      choices: ['N/4', 'N/2', 'N', '2N'],
      answer: 0,
      explain: 'Each signal element carries 2 bits (r = 2) and the average case has c = 1/2, so S = c × N × 1/r = ½ × N × ½ = N/4 (slides 38 and 46). The r = 1/2 printed in the slide’s box is a mistake.' },
    { id: 'l03a.q016', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L03 p13; L03 p14',
      q: 'The receiver’s clock runs <b>faster</b> than the sender’s clock. What happens?',
      choices: ['Nothing — the receiver re-times itself automatically', 'The receiver misses bits and sees a shorter stream', 'The bits arrive in a different order',
        'The receiver reads extra bits (for example 1001 bps instead of 1000 bps) and misinterprets the stream'],
      answer: 3,
      explain: 'If the receiver clock is faster or slower than the sender’s, the receiver misinterprets the incoming bit stream (slide 13). With a 0.1% faster clock it receives 1001 bps instead of 1000 bps (slide 14) — extra bits, not missing ones.' },
    { id: 'l03a.q017', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L03 p44',
      q: 'In <b>MLT-3</b>, the signal is at +V and the next bit is a 1. Where does the level go?',
      choices: ['−V', '0 V', 'It stays at +V', '+2V'],
      answer: 1,
      explain: 'MLT-3: a 0 keeps the level; a 1 moves ±V → 0, and 0 → the opposite of the last nonzero level. From +V a 1 goes to 0 V (the next 1 would then go to −V), so 1111 cycles + 0 − 0 (slide 44).' },
    { id: 'l03a.q018', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L03 p59',
      q: 'Which pattern does <b>B8ZS</b> substitute for eight consecutive zeros?',
      choices: ['000VB0VB', 'B00V', '000V', 'VB0VB000'],
      answer: 0,
      explain: 'B8ZS uses 000VB0VB, where V is a violation of the line-encoding rule and B follows the bipolar rule (slide 59). B00V and 000V are the HDB3 patterns for four zeros.' },
    { id: 'l03a.q019', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L03 p51; L03 p52',
      q: 'In the 4B/5B table, which 5-bit word replaces the data word <b>0000</b>?',
      choices: ['01001', '11101', '11110', '10101'],
      answer: 2,
      explain: 'From the table on slide 51: 0000 → 11110. For comparison 0001 → 01001, 0011 → 10101 and 1111 → 11101; slide 52 shows 0000, 0001 and 1111 being substituted.' },
    { id: 'l03a.q020', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L03 p15; L03 p16',
      q: 'What does <b>error detection</b> mean in the context of line coding?',
      choices: ['The receiver corrects the corrupted bit automatically', 'A signal pattern that is not part of the code arrives, so the receiver knows a symbol error occurred',
        'The signal is immune to noise and cannot be corrupted', 'The sender repeats every bit three times'],
      answer: 1,
      explain: 'Slide 15: some codes are built so that a particular signal transition is not part of the code; when it occurs, the receiver knows a symbol error occurred. Slide 16 calls a signal that cannot be corrupted “immune” to noise — stronger than error detection.' },
    { id: 'l03a.q021', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L03 p48',
      q: 'According to the slides, what does block coding do for the line code that follows it?',
      choices: ['It lowers the bit rate by 20%', 'It removes the need for a line code', 'It makes every bit have a mid-bit transition',
        'It adds redundancy so that bit combinations giving DC components or poor synchronization are avoided'],
      answer: 3,
      explain: 'Slide 48: block coding adds redundancy (extra bits), and the resulting bit stream prevents certain bit combinations that, used with line encoding, would give DC components or poor synchronization. It raises the bit rate (4B/5B: × 5/4), it does not lower it.' },

    /* ===================== Form B: Identification (5) ===================== */
    { id: 'l03a.q022', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L03 p11',
      q: 'The drift of the receiver’s running average (the baseline) caused by a long string of 0s or 1s, which makes correct decoding difficult.',
      answer: 'Baseline wandering', accept: ['baseline wander'],
      explain: 'The baseline is the receiver’s running average of the received signal power; long runs of one level make it drift (slide 11).' },
    { id: 'l03a.q023', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L03 p22',
      q: 'The polar NRZ version in which the <i>change or lack of change</i> in polarity gives the bit: a 1 inverts the level, a 0 does not.',
      answer: 'NRZ-I', accept: ['NRZ-Inversion', 'NRZ inversion', 'Non-Return-to-Zero Inversion', 'Non Return to Zero Inversion', 'NRZ-Invert', 'NRZ inverted', 'Non-Return-to-Zero Inverted'],
      explain: 'NRZ-I (NRZ-Inversion): the inversion or lack of inversion determines the bit. In NRZ-L the level itself determines the bit (slide 24).' },
    { id: 'l03a.q024', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L03 p13',
      q: 'The property of a line code that lets the receiver keep its clock in step with the sender’s clock by using the transitions in the signal itself.',
      answer: 'Self-synchronization', accept: ['self synchronizing', 'self-synchronizing', 'self-clocking', 'self clocking', 'selfsynchronization'],
      explain: 'Clocks at the sender and the receiver must have the same bit interval (slide 13); a self-synchronizing code carries the timing in its transitions. Scrambling also aims at “self clocking” (slide 57).' },
    { id: 'l03a.q025', topic: T, pool: 'B', type: 'id', diff: 2, ref: 'L03 p59',
      q: 'In the B8ZS pattern 000VB0VB, what does the letter <b>V</b> stand for?',
      answer: 'Violation', accept: ['a violation', 'violation pulse', 'violate'],
      explain: 'V stands for violation — a pulse that violates the line-encoding rule (it repeats the polarity of the previous pulse); B stands for bipolar — a pulse that follows the rule (slide 59).' },
    { id: 'l03a.q026', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L03 p20',
      q: 'The line-coding family in which <i>all</i> signal levels are on one side of the time axis (NRZ is the example).',
      answer: 'Unipolar', accept: ['unipolar NRZ', 'unipolar encoding', 'unipolar coding', 'unipolar scheme'],
      explain: 'Slide 20: unipolar schemes keep every level above (or below) the axis; NRZ is the example. It is simple but costly in power, and prone to baseline wandering and DC components.' },

    /* ===================== Diagnostic (5; two numeric) ===================== */
    { id: 'l03a.q027', topic: T, pool: 'diag', type: 'num', diff: 2, ref: 'L03 p54; L03 p25',
      q: 'Data at 8 Mbps is block-coded with 4B/5B and then sent with NRZ-I. What minimum bandwidth is needed (average case)?',
      num: { value: 5e6, tol: 0.01, rel: true, unit: 'Hz' },
      explain: '4B/5B: N′ = 8 × 5/4 = 10 Mbps. NRZ-I: S = ½ × 10 Mbps × 1 = 5 Mbaud, and B<sub>min</sub> = S = 5 MHz.' },
    { id: 'l03a.q028', topic: T, pool: 'diag', type: 'mcq', diff: 1, ref: 'L03 p22; L03 p23',
      q: 'In the slide convention, how does <b>NRZ-I</b> represent a 1?',
      choices: ['As +V', 'As −V', 'By inverting the level at the start of the bit', 'By a transition in the middle of the bit'],
      answer: 2,
      explain: 'NRZ-I: a 1 inverts the level (the change itself carries the bit) and a 0 keeps it. NRZ-L is the one where the level itself carries the bit.' },
    { id: 'l03a.q029', topic: T, pool: 'diag', type: 'tf', diff: 2, ref: 'L03 p30',
      q: 'A long run of 0s is not a synchronization problem for Manchester coding, because every bit has a transition in the middle.',
      answer: true,
      explain: 'In Manchester and differential Manchester coding, the transition in the middle of the bit is used for synchronization (slide 30), whatever the data are.' },
    { id: 'l03a.q030', topic: T, pool: 'diag', type: 'id', diff: 1, ref: 'L03 p60',
      q: 'The scrambling technique that replaces four consecutive zeros with 000V or B00V.',
      answer: 'HDB3', accept: ['HDB-3', 'HDB3 scrambling'],
      explain: 'HDB3 chooses 000V (odd number of nonzero pulses since the last substitution) or B00V (even), slides 60–61. B8ZS is the eight-zero technique.' },
    { id: 'l03a.q031', topic: T, pool: 'diag', type: 'num', diff: 2, ref: 'L03 p14',
      q: 'The receiver clock is 0.5% faster than the sender clock. How many extra bits per second does the receiver read when the data rate is 1 Mbps?',
      num: { value: 5000, tol: 0.01, rel: true, unit: 'bps' },
      explain: '1,000,000 × 0.5/100 = 5000 extra bps — the receiver gets 1,005,000 bps (slide 14 does the same with 0.1%).' },

    /* ===================== General: quick checks, practice, flashcards ===================== */
    { id: 'l03a.q032', topic: T, type: 'mcq', diff: 2, ref: 'L03 p22; L03 p23',
      q: 'In the NRZ-L figure on slide 23, which level represents a <b>0</b>?',
      choices: ['−V', '+V', '0 V', 'The level alternates between +V and −V'],
      answer: 1,
      explain: 'The slide-23 figure shows NRZ-L with 0 = +V and 1 = −V. The text on slide 22 says “+V for 1 and −V for 0”, which contradicts the figure. The polarity is only a convention — state your legend — but this kit follows the figure.' },
    { id: 'l03a.q033', topic: T, type: 'tf', diff: 2, ref: 'L03 p29; L03 p5',
      q: 'In the slides’ Manchester figure, a 1 is a <b>high→low</b> transition.',
      answer: false, fix: 'A 0 is high→low and a 1 is low→high (slide 29 figure; the text on slide 5 lists them the other way round).',
      explain: 'Slide 29 labels “0 is high→low, 1 is low→high”. Slide 5’s example (1 → +V and −V, 0 → −V and +V) is the reverse; follow the figure, and state your legend if you use the opposite.' },
    { id: 'l03a.q034', topic: T, type: 'num', diff: 1, ref: 'L03 p24',
      q: 'NRZ-L carries 10 Mbps. What is its average signal rate?',
      num: { value: 5e6, tol: 0.01, rel: true, unit: 'baud' },
      explain: 'NRZ-L has r = 1 and c = 1/2 on average: S = ½ × 10 Mbps × 1 = 5 Mbaud (N/2, slide 24).' },
    { id: 'l03a.q035', topic: T, type: 'mcq', diff: 1, ref: 'L03 p27; L03 p29',
      q: 'RZ and Manchester both have r = 1/2. What does that mean?',
      choices: ['Two data elements are carried by one signal element', 'One data element is carried by one signal element', 'Each data element is encoded as two signal elements', 'Half of the data elements are not sent'],
      answer: 2,
      explain: 'r is the number of data elements carried by a signal element. r = 1/2 means each bit uses two signal elements (the two halves of the bit), so S_avg = N — twice the signal rate of NRZ.' },
    { id: 'l03a.q036', topic: T, type: 'tf', diff: 2, ref: 'L03 p33; L03 p46',
      q: 'AMI has no DC component and no baseline wandering.',
      answer: true,
      explain: 'Slide 33 says so: the alternating 1s cancel. (The summary table on slide 46 marks AMI “DC” — that contradicts slide 33; AMI’s real weakness is no self-synchronization during long runs of 0s.)' },
    { id: 'l03a.q037', topic: T, type: 'multi', diff: 2, ref: 'L03 p26; L03 p28',
      q: 'Select <b>all</b> line codes that have a level transition in the middle of every bit.',
      choices: ['NRZ-L', 'RZ', 'Manchester', 'Differential Manchester', 'AMI'], answer: [1, 2, 3],
      explain: 'RZ (to zero), Manchester and differential Manchester all change level in the middle of every bit (slides 26 and 28). NRZ-L and AMI have no mid-bit transition.' },
    { id: 'l03a.q038', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L03 p51',
      q: 'In the 4B/5B table, the control sequence <b>11111</b> is named:',
      answer: 'Idle', accept: ['I', 'I (Idle)', 'Idle (I)'],
      explain: 'Slide 51 control sequences: Q (Quiet) 00000, I (Idle) 11111, H (Halt) 00100, J and K (Start delimiters) 11000 and 10001, T (End delimiter) 01101, S (Set) 11001, R (Reset) 00111.' },
    { id: 'l03a.q039', topic: T, type: 'mcq', diff: 2, ref: 'L03 p53',
      q: 'A 4-bit data word has 2<sup>4</sup> = 16 combinations and a 5-bit word has 2<sup>5</sup> = 32. How many 5-bit words are left over in 4B/5B?',
      choices: ['8', '16', '24', '32'],
      answer: 1,
      explain: '32 − 16 = 16 extra words, some of which are used for control and signalling (slide 53). The slide prints this as “24 / 25 = 32 / 32 − 26 = 16”, with the superscripts lost.' },
    { id: 'l03a.q040', topic: T, type: 'num', diff: 1, ref: 'L03 p54',
      q: 'A 100 Mbps data stream goes through 4B/5B block coding. What is the bit rate on the line afterwards?',
      num: { value: 125e6, tol: 0.01, rel: true, unit: 'bps' },
      explain: '4B/5B multiplies the rate by 5/4: 100 × 5/4 = 125 Mbps.' },
    { id: 'l03a.q041', topic: T, type: 'tf', diff: 2, ref: 'L03 p60',
      q: 'In HDB3, the substitution <b>000V</b> is used when the number of nonzero pulses since the last substitution is <b>even</b>.',
      answer: false, fix: 'An odd count uses 000V; an even count uses B00V — so the total number of nonzero pulses is even either way.',
      explain: 'Slide 60: even → B00V, odd → 000V, “to make total # of non zero pulses even”.' },
    { id: 'l03a.q042', topic: T, type: 'mcq', diff: 1, ref: 'L03 p48',
      q: 'Which is the correct order of the three steps of block coding?',
      choices: ['Division, substitution, combination', 'Substitution, division, combination', 'Combination, substitution, division', 'Division, combination, substitution'],
      answer: 0,
      explain: 'Block coding divides the stream into m-bit groups, substitutes each with an n-bit group, then combines the n-bit groups into a stream (slides 48–49).' },
    { id: 'l03a.q043', topic: T, type: 'mcq', diff: 2, ref: 'L03 p8; L03 p25',
      q: 'In S = c × N × 1/r, what is <b>c</b>?',
      choices: ['The number of signal levels', 'The channel capacity', 'The carrier frequency', 'The case factor (worst case 1, best case 0, average 1/2)'],
      answer: 3,
      explain: 'c is the case factor: worst case 1, best case 0, and 1/2 for the average case (slides 8 and 25). N is the data rate and r the ratio of data elements to signal elements.' },
    { id: 'l03a.q044', topic: T, type: 'num', diff: 2, ref: 'L03 p7; L03 p8',
      q: 'A signal encodes four data elements as three signal elements (r = 4/3). The bit rate is 8 kbps and c = 1/2. What is the average baud rate?',
      num: { value: 3000, tol: 0.01, rel: true, unit: 'baud' },
      explain: 'S = c × N × 1/r = ½ × 8000 × 3/4 = 3000 baud.' },
    { id: 'l03a.q045', topic: T, type: 'id', diff: 2, ref: 'L03 p48',
      q: 'The slash in xB/yB notation (as in 4B/5B) distinguishes block coding from which other kind of coding?',
      answer: 'Multilevel coding', accept: ['multilevel', 'multi-level coding', 'multilevel schemes', 'multilevel code', 'mBnL'],
      explain: 'Slide 48: block coding is distinguished from multilevel coding by the use of the slash — xB/yB — while multilevel codes are written mBnL (2B1Q, 8B6T).' },
    { id: 'l03a.q046', topic: T, type: 'mcq', diff: 2, ref: 'L03 p44',
      q: 'In MLT-3, what does a <b>0</b> do to the signal level?',
      choices: ['Moves it to the next level', 'Resets it to 0 V', 'Leaves it unchanged', 'Inverts it'],
      answer: 2,
      explain: 'MLT-3: a 0 keeps the level; only a 1 moves the signal round the cycle 0, +V, 0, −V (slide 44).' },
    { id: 'l03a.q047', topic: T, type: 'tf', diff: 2, ref: 'L03 p38; L03 p46',
      q: 'The box on slide 38 gives r = 1/2 for 2B1Q, and that is correct.',
      answer: false, fix: 'Two data bits map to one signal element, so r = 2 (which is what gives S_avg = N/4).',
      explain: '2B1Q = 2 binary → 1 quaternary, so r = 2 and S = c × N × 1/r = ½ × N × ½ = N/4, the value in the slide’s own box and in the table on slide 46. The printed r = 1/2 is a slip.' },
    { id: 'l03a.q048', topic: T, type: 'mcq', diff: 2, ref: 'L03 p15; L03 p16',
      q: 'Which of these does the slide describe as <i>stronger</i> than error detection?',
      choices: ['Noise immunity — the signal cannot be corrupted', 'Self-synchronization', 'Baseline wandering', 'A lower baud rate'],
      answer: 0,
      explain: 'Slide 16: some techniques make the transmitted signal “immune” to noise and interference — it cannot be corrupted, which is stronger than error detection (slide 15: noticing that an invalid pattern arrived).' },
    { id: 'l03a.q049', topic: T, type: 'num', diff: 2, ref: 'L03 p38; L03 p46',
      q: 'A system sends 8 Mbps with 2B1Q. What is the average signal rate?',
      num: { value: 2e6, tol: 0.01, rel: true, unit: 'baud' },
      explain: 'S_avg = N/4 for 2B1Q (r = 2, c = 1/2): 8 Mbps / 4 = 2 Mbaud.' },
    { id: 'l03a.q050', topic: T, type: 'mcq', diff: 2, ref: 'L03 p42',
      q: '4D-PAM5 sends 1 Gbps over four wires. What does each wire carry?',
      choices: ['1 Gbps at 1 GBd', '250 Mbps at 125 MBd', '250 Mbps at 250 MBd', '125 Mbps at 125 MBd'],
      answer: 1,
      explain: 'Slide 42: the 1 Gbps stream is split into four 250 Mbps streams, each sent at 125 MBd (the five-level PAM carries 2 bits per signal element).' },
    { id: 'l03a.q051', topic: T, type: 'mcq', diff: 1, ref: 'L03 p55',
      q: 'Which blocks make up an 8B/10B encoder?',
      choices: ['5B/6B and 3B/4B encoders plus a disparity controller', 'Two 4B/5B encoders', 'A scrambler and an AMI encoder', 'A 2B1Q encoder and an HDB3 encoder'],
      answer: 0,
      explain: 'Slide 55: the 8-bit block is split into 5B/6B and 3B/4B encoding, and a disparity controller produces the 10-bit block. Slide 56: the extra redundancy lets it avoid long runs of one level.' },
    { id: 'l03a.q052', topic: T, type: 'id', diff: 2, ref: 'L03 p59',
      q: 'In the B8ZS pattern 000VB0VB, what does the letter <b>B</b> stand for?',
      answer: 'Bipolar', accept: ['bipolar pulse', 'bipolar rule'],
      explain: 'Slide 59: B stands for bipolar — it implements the bipolar line-encoding rule (alternating polarity); V stands for violation.' },
    { id: 'l03a.q053', topic: T, type: 'tf', diff: 1, ref: 'L03 p6',
      q: 'The goal of line coding is to increase the data rate while reducing the baud rate.',
      answer: true,
      explain: 'Slide 6: “Goal is to increase the data rate whilst reducing the baud rate.” Codes with r > 1 (2B1Q, 8B6T, 4D-PAM5) do this; Manchester (r = 1/2) does the opposite.' },
    { id: 'l03a.q054', topic: T, type: 'mcq', diff: 2, ref: 'L03 p19',
      q: 'In the slides’ tree of line-coding schemes, MLT-3 belongs to which family?',
      choices: ['Polar', 'Bipolar', 'Multilevel', 'Multitransition'],
      answer: 3,
      explain: 'Slide 19: Unipolar (NRZ); Polar (NRZ, RZ, biphase); Bipolar (AMI, pseudoternary); Multilevel (2B1Q, 8B6T, 4D-PAM5); Multitransition (MLT-3). The summary table on slide 46 mislabels the last family “Multiline”.' },
    { id: 'l03a.q055', topic: T, type: 'num', diff: 2, ref: 'L03 p14',
      q: 'The receiver clock is 2% faster than the sender clock. How many extra bits per second does it read when the data rate is 5 kbps?',
      num: { value: 100, tol: 0.01, rel: true, unit: 'bps' },
      explain: '5000 × 2/100 = 100 extra bps — the receiver gets 5100 bps instead of 5000 bps.' },
    { id: 'l03a.q056', topic: T, type: 'mcq', diff: 1, ref: 'L03 p7',
      q: 'On slide 7(c) the data stream 11 | 01 | 11 is sent as one signal element per pair of bits. What is r?',
      choices: ['1/2', '1', '2', '4/3'],
      answer: 2,
      explain: 'r is the number of data elements carried by one signal element: two data elements per signal element gives r = 2. The four cases on slide 7 are r = 1, 1/2, 2 and 4/3.' },
    { id: 'l03a.q057', topic: T, type: 'num', diff: 2, ref: 'L03 p10',
      q: 'A noiseless channel has B = 4 kHz and the signal uses L = 4 levels. What is the maximum data rate (N<sub>max</sub> = 2 × B × log<sub>2</sub> L)?',
      num: { value: 16e3, tol: 0.01, rel: true, unit: 'bps' },
      explain: 'N<sub>max</sub> = 2 × 4000 × log<sub>2</sub> 4 = 2 × 4000 × 2 = 16,000 bps (the Nyquist formula, recalled on slide 10).' },
    { id: 'l03a.q058', topic: T, pool: 'A', type: 'id', diff: 2, ref: 'L03 p55; L03 p56',
      q: 'The block code whose encoder splits each 8-bit block between a 5B/6B encoder and a 3B/4B encoder and passes the result through a disparity controller.',
      answer: '8B/10B', accept: ['8B/10B encoding', '8B/10B block coding', '8B/10B block encoding', '8B/10B block code', '8B/10B code'],
      explain: 'Slide 55: 8-bit block → 5B/6B + 3B/4B encoding → disparity controller → 10-bit block. Slide 56: the extra redundancy lets it choose code words that avoid long runs of one level (DC components).' },
    { id: 'l03a.e002', topic: T, pool: 'B', type: 'essay', diff: 2, ref: 'L03 pp57-61',
      q: 'Why does <b>AMI</b> need scrambling? Explain how <b>B8ZS</b> and <b>HDB3</b> work, and draw B8ZS for the bits <b class="mono">100000000</b> when the last pulse sent before this stream was −V (so the 1 is sent as +V). Mark each V and B.',
      rubric: [
        { pts: 1, point: 'Problem: a long run of 0s in AMI is a flat 0 V line, so the receiver loses synchronization; scrambling fixes it without increasing the bandwidth.' },
        { pts: 1, point: 'B8ZS replaces eight consecutive 0s with 000VB0VB: V (violation) has the same polarity as the pulse before it, B (bipolar) follows the AMI alternation.' },
        { pts: 1, point: 'HDB3 replaces four consecutive 0s: 000V if the number of nonzero pulses since the last substitution is odd, B00V if it is even.' },
        { pts: 1, point: 'The receiver recognizes the violations and turns each pattern back into 0s; scrambling keeps the signal self-clocking with no low frequencies and no wider bandwidth (slide 57).' },
        { pts: 1, point: 'Drawing: + 0 0 0 + − 0 − + (the 1 is + because the pulse before was −; then 000VB0VB with V = +, B = −, V = −, B = +).' }],
      model: '<p>In AMI a 0 is sent as 0 V, so a long run of 0s is a flat line with no transitions and the receiver loses synchronization. <b>Scrambling</b> replaces such runs with a pattern containing deliberate <b>violations</b> that the receiver can recognize; unlike block coding it does not increase the bandwidth. <span class="chip ref">L03 p57</span></p>' +
        '<p><b>B8ZS</b> replaces eight consecutive 0s with <b>000VB0VB</b>. V is a violation — a pulse with the same polarity as the one before it; B is a bipolar pulse that follows the AMI rule (opposite polarity). <span class="chip ref">L03 p59</span> ' +
        '<b>HDB3</b> replaces four consecutive 0s with <b>000V</b> if the number of nonzero pulses since the last substitution is odd, or <b>B00V</b> if it is even, so the total stays even. <span class="chip ref">L03 p60</span> <span class="chip ref">L03 p61</span></p>' +
        '<p>For <span class="mono">100000000</span> after a −V pulse, the 1 is sent as +V; the eight 0s become 000VB0VB = <b class="mono">0 0 0 + − 0 − +</b>.</p>' +
        '<figure data-fig="l03a.scramble" data-code="b8zs" data-bits="100000000" data-prev="-1"></figure>' +
        '<figure data-fig="l03a.scramble" data-code="hdb3" data-bits="1100001000000000" data-prev="-1" data-parity="0" data-caption="HDB3, slide 61: even count → B00V, odd → 000V."></figure>',
      explain: 'Award each rubric point independently.' }
  ]);
})();
