/* L03b question bank (PCM, delta modulation, transmission modes). Owner: Lead. */
(function () {
  'use strict';
  var T = 'l03b';
  KIT.bank.add([
    /* ----- Form A: MCQ (4) + Identification (3) ----- */
    { id: 'l03b.q001', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L03 p62',
      q: 'Which is the correct order of the three PCM steps?',
      choices: ['Quantization → sampling → encoding', 'Sampling → quantization → binary encoding', 'Encoding → sampling → quantization', 'Sampling → encoding → quantization'],
      answer: 1, explain: 'PCM samples the analog signal (PAM), quantizes each sample to a zone midpoint, then encodes the zone number in binary.' },
    { id: 'l03b.q002', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L03 p66; L03 p70',
      q: 'A low-pass signal contains frequencies from 0 to 5 kHz. What is the minimum sampling rate?',
      choices: ['5000 samples/s', '2500 samples/s', '20,000 samples/s', '10,000 samples/s'], answer: 3,
      explain: 'Nyquist: f<sub>s</sub> ≥ 2 × f<sub>max</sub> = 2 × 5 kHz = 10,000 samples/s.' },
    { id: 'l03b.q003', topic: T, pool: 'A', type: 'mcq', diff: 2, ref: 'L03 p75; L03 p79',
      q: 'A signal is quantized into L = 32 levels and sampled at 8000 samples/s. What is the bit rate?',
      choices: ['40 kbps', '256 kbps', '32 kbps', '64 kbps'], answer: 0,
      explain: 'n<sub>b</sub> = log₂32 = 5 bits per sample, so N = 5 × 8000 = 40 kbps.' },
    { id: 'l03b.q004', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L03 p92',
      q: 'In asynchronous transmission, each byte is framed by:',
      choices: ['a start bit 1 and a stop bit 0', 'a start bit 0 and one or more stop bits 1', 'a flag byte at each end', 'no extra bits at all'], answer: 1,
      explain: 'One start bit (0) begins every byte and one or more stop bits (1) end it; gaps may follow.' },
    { id: 'l03b.q005', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L03 p64',
      q: 'The sampling method that holds each sample at one constant amplitude for the pulse duration.',
      answer: 'Flat-top sampling', accept: ['flat top sampling', 'flat-top', 'flat top', 'sample and hold'],
      explain: 'Flat-top sampling is "sample and hold": like natural sampling, but each pulse keeps a single amplitude.' },
    { id: 'l03b.q006', topic: T, pool: 'A', type: 'id', diff: 2, ref: 'L03 p78',
      q: 'The technique that compresses sample values at the sender and expands them at the receiver to keep the SNQR more even across amplitudes.',
      answer: 'Companding', accept: ['compression and expansion', 'compand'],
      explain: 'Companding = compressing (logarithmic zones) then expanding; it helps low-amplitude signals that suffer most from quantization error.' },
    { id: 'l03b.q007', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L03 p84',
      q: 'The digitization scheme that sends a single bit per sample: 1 if the signal rose above the staircase, 0 if it did not.',
      answer: 'Delta modulation', accept: ['DM'],
      explain: 'Delta modulation sends only the direction of change, one bit per sample.' },

    /* ----- Form B: MCQ (4) + Identification (3) ----- */
    { id: 'l03b.q008', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L03 p71',
      q: 'A complex bandpass signal has a bandwidth of 300 kHz. What is its minimum sampling rate?',
      choices: ['600,000 samples/s', '300,000 samples/s', 'It cannot be determined from the bandwidth alone', '150,000 samples/s'], answer: 2,
      explain: 'Nyquist needs the highest frequency; knowing only the width of the band does not tell us f<sub>max</sub> (slide Example 8).' },
    { id: 'l03b.q009', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L03 p72',
      q: 'For a range of −10 V to +10 V and L = 4 zones, what is the zone height Δ?',
      choices: ['2.5 V', '5 V', '10 V', '20 V'], answer: 1,
      explain: 'Δ = (max − min)/L = (10 − (−10))/4 = 5 V.' },
    { id: 'l03b.q010', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L03 p81',
      q: 'Which component of a PCM decoder smooths the held staircase back into an analog signal?',
      choices: ['A comparator', 'A delay unit', 'A quantizer', 'A low-pass filter'], answer: 3,
      explain: 'The hold circuit makes a staircase; a low-pass filter with cutoff = f<sub>max</sub> smooths it into the analog signal.' },
    { id: 'l03b.q011', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L03 p77',
      q: 'Increasing the number of quantization levels L …',
      choices: ['raises the quantization error', 'lowers the quantization error but raises the bit rate', 'lowers both the error and the bit rate', 'has no effect on the bit rate'], answer: 1,
      explain: 'More zones → smaller Δ → smaller error, but more bits per sample → higher bit rate.' },
    { id: 'l03b.q012', topic: T, pool: 'B', type: 'id', diff: 2, ref: 'L03 p96',
      q: 'Serial transmission in which uneven gaps between frames are not allowed; bits flow with fixed, equal gaps.',
      answer: 'Isochronous transmission', accept: ['isochronous'],
      explain: 'Isochronous transmission cannot have uneven gaps between frames.' },
    { id: 'l03b.q013', topic: T, pool: 'B', type: 'id', diff: 2, ref: 'L03 p81',
      q: 'The PCM decoder circuit that holds each pulse amplitude until the next pulse arrives.',
      answer: 'Hold circuit', accept: ['hold', 'sample and hold circuit'],
      explain: 'The hold circuit turns the pulses into a staircase, which the low-pass filter then smooths.' },
    { id: 'l03b.q014', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L03 p64',
      q: 'The name of the sampled signal — pulses whose heights are the (non-integer) sample values.',
      answer: 'PAM', accept: ['pulse amplitude modulation', 'PAM signal'],
      explain: 'Sampling is called pulse amplitude modulation; its output still has analog values.' },

    /* ----- Diagnostic (3) ----- */
    { id: 'l03b.q015', topic: T, pool: 'diag', type: 'num', diff: 2, ref: 'L03 p80',
      q: 'Voice (0–4 kHz) is digitized at the Nyquist rate with 8 bits per sample. What is the bit rate?',
      num: { value: 64000, tol: 0.01, rel: true, unit: 'bps' },
      explain: 'f<sub>s</sub> = 2 × 4000 = 8000 samples/s; N = 8 × 8000 = 64 kbps.' },
    { id: 'l03b.q016', topic: T, pool: 'diag', type: 'mcq', diff: 2, ref: 'L03 p75; L03 p76',
      q: 'Range −20 V to +20 V, L = 8 (Δ = 5 V, zones coded 000 at the bottom). Which code does the sample +16.2 V get?',
      choices: ['110', '111', '101', '011'], answer: 1,
      explain: '+16.2 V lies in the top zone, +15 to +20 V (zone 7) → 111. Slide 76 codes 16.2 V as 111.' },
    { id: 'l03b.q017', topic: T, pool: 'diag', type: 'id', diff: 1, ref: 'L03 p92',
      q: 'Serial transmission in which every byte gets a start bit and stop bit(s), and gaps may occur between bytes.',
      answer: 'Asynchronous transmission', accept: ['asynchronous', 'asynchronous serial transmission'],
      explain: 'Asynchronous transmission is "asynchronous at the byte level": start/stop bits, gaps allowed.' },

    /* ----- General ----- */
    { id: 'l03b.q018', topic: T, type: 'mcq', diff: 1, ref: 'L03 p64',
      q: 'Which sampling method produces short pulses whose tops follow the shape of the analog signal?',
      choices: ['Ideal', 'Natural', 'Flat-top', 'Delta'], answer: 1,
      explain: 'Natural sampling keeps the signal\'s shape on each pulse top; flat-top holds one value; ideal uses impulses.' },
    { id: 'l03b.q019', topic: T, type: 'tf', diff: 1, ref: 'L03 p68',
      q: 'Sampling a sine wave at the Nyquist rate gives a good approximation; oversampling gives the same approximation with redundant samples.',
      answer: true, explain: 'That is the lesson of slide 68, parts (a) and (b); undersampling (c) gives a false wave.' },
    { id: 'l03b.q020', topic: T, type: 'num', diff: 2, ref: 'L03 p83',
      q: 'A low-pass signal (0–10 kHz) is digitized with 6 bits per sample. What minimum bandwidth does the digital signal need (NRZ-type line code)?',
      num: { value: 60000, tol: 0.01, rel: true, unit: 'Hz' },
      explain: 'B<sub>min</sub> = n<sub>b</sub> × f<sub>max</sub> = 6 × 10 kHz = 60 kHz (compare slide 83: 8 × 4 kHz = 32 kHz).' },
    { id: 'l03b.q021', topic: T, type: 'tf', diff: 1, ref: 'L03 p79; L03 p83',
      q: 'A digitized signal always needs less bandwidth than the original analog signal.',
      answer: false, fix: 'It always needs MORE bandwidth (e.g. 32 kHz instead of 4 kHz for 8-bit voice) — the price of robustness.',
      explain: 'Slide 79: a digitized signal will always need more bandwidth than the original analog signal.' },
    { id: 'l03b.q022', topic: T, type: 'id', diff: 1, ref: 'L03 p72',
      q: 'The symbol for the height of each quantization zone, equal to (max − min)/L.',
      answer: 'Delta', accept: ['Δ', 'zone height', 'step size', 'zone width'],
      explain: 'Δ = (max − min)/L.' },
    { id: 'l03b.q023', topic: T, type: 'mcq', diff: 2, ref: 'L03 p84',
      q: 'In delta modulation, large and fast changes in the signal cause:',
      choices: ['no errors, because each bit is a full sample', 'large errors, because the staircase moves only one step δ per sample', 'the bit rate to double', 'the sampling rate to drop'],
      answer: 1, explain: 'The staircase can move only ±δ per sample, so it cannot keep up with large changes.' },
    { id: 'l03b.q024', topic: T, type: 'multi', diff: 2, ref: 'L03 p94',
      q: 'Select <b>all</b> statements that are true of synchronous transmission.',
      choices: ['Bits are sent one after another without start or stop bits', 'Gaps between bytes are allowed', 'The receiver is responsible for grouping the bits', 'Bytes are grouped into frames identified by start and end bytes'],
      answer: [0, 2, 3], explain: 'Synchronous transmission has no start/stop bits and no gaps; the receiver groups bits; frames carry start and end bytes.' },
    { id: 'l03b.q025', topic: T, type: 'num', diff: 1, ref: 'L03 p75',
      q: 'How many bits per sample are needed for L = 128 quantization levels?',
      num: { value: 7, tol: 0, rel: false, unit: '' }, explain: 'n<sub>b</sub> = log₂128 = 7.' },
    { id: 'l03b.q026', topic: T, type: 'mcq', diff: 1, ref: 'L03 p89; L03 p90',
      q: 'In the slides\' parallel transmission of a byte, how many bits are sent with each clock tick?',
      choices: ['1', '2', '8', 'It depends on the gaps'], answer: 2,
      explain: 'Parallel mode sends the 8 bits together over 8 lines.' },
    { id: 'l03b.q027', topic: T, type: 'tf', diff: 1, ref: 'L03 p75',
      q: 'In the slides\' quantization example, code 000 is assigned to the highest zone (+15 to +20 V).',
      answer: false, fix: 'Code 000 is the LOWEST zone (−20 to −15 V); 111 is +15 to +20 V.',
      explain: 'Zones are numbered from the bottom.' },
    { id: 'l03b.q028', topic: T, type: 'id', diff: 2, ref: 'L03 p88',
      q: 'The scheme that quantizes the difference between samples with several bits, improving on delta modulation\'s single bit.',
      answer: 'DPCM', accept: ['delta PCM', 'differential PCM', 'differential pulse code modulation'],
      explain: 'Delta PCM (DPCM): more bits per difference → more levels → higher accuracy.' },
    { id: 'l03b.q029', topic: T, type: 'mcq', diff: 1, ref: 'L03 p69',
      q: 'Telephone companies digitize voice by assuming a maximum frequency of:',
      choices: ['2 kHz', '4 kHz', '8 kHz', '64 kHz'], answer: 1,
      explain: '4000 Hz, so the sampling rate is 8000 samples/s.' },
    { id: 'l03b.e001', topic: T, pool: 'A', type: 'essay', diff: 2, ref: 'L03 pp62-79',
      q: 'Explain how <b>PCM</b> turns an analog signal into a digital one. Draw a short analog signal and show what each of the three steps does to it, then explain why the sampling rate must be at least twice the highest frequency. You may draw, explain, or both.',
      rubric: [
        { pts: 1, point: 'Sampling: the signal is measured every T<sub>s</sub> (f<sub>s</sub> = 1/T<sub>s</sub>); the result is PAM — pulses that still have analog (non-integer) heights.' },
        { pts: 1, point: 'Quantization: the range is split into L zones of height Δ = (max − min)/L and each sample is replaced by its zone midpoint; the error is at most Δ/2.' },
        { pts: 1, point: 'Encoding: each zone number is sent as n<sub>b</sub> = log<sub>2</sub>L bits, so the bit rate is N = n<sub>b</sub> × f<sub>s</sub>.' },
        { pts: 1, point: 'Nyquist: f<sub>s</sub> ≥ 2 f<sub>max</sub>; sampled more slowly, the samples trace a false, slower wave — so the signal is filtered first to limit f<sub>max</sub>.' },
        { pts: 1, point: 'A labelled drawing (or an equally clear description) of the samples, the staircase of quantized values and the codes.' }],
      model: '<p><b>PCM has three steps.</b> <b>Sampling</b> measures the analog signal every T<sub>s</sub> seconds (f<sub>s</sub> = 1/T<sub>s</sub>); the result is a PAM signal — pulses whose heights are still analog values. <span class="chip ref">L03 p64</span> ' +
        '<b>Quantization</b> divides the range from min to max into L zones of height Δ = (max − min)/L and replaces each sample by the midpoint of its zone; the difference is the quantization error, at most Δ/2. <span class="chip ref">L03 p72</span> <span class="chip ref">L03 p78</span> ' +
        '<b>Encoding</b> sends each zone number as an n<sub>b</sub>-bit code word, n<sub>b</sub> = log<sub>2</sub>L, so the bit rate is N = n<sub>b</sub> × f<sub>s</sub> (8 bits × 8000 samples/s = 64 kbps for voice). <span class="chip ref">L03 p75</span> <span class="chip ref">L03 p79</span> <span class="chip ref">L03 p69</span> <span class="chip ref">L03 p80</span></p>' +
        '<figure data-fig="l03b.pcm"></figure>' +
        '<p><b>Why 2 × f<sub>max</sub>:</b> by the Nyquist theorem the sampling rate must be at least twice the highest frequency in the signal. Sampled more slowly, the samples trace a false, slower wave and the original cannot be rebuilt, so the signal is filtered first to limit f<sub>max</sub>. <span class="chip ref">L03 p62</span> <span class="chip ref">L03 p66</span> <span class="chip ref">L03 p68</span></p>' +
        '<figure data-fig="l03b.sampling"></figure>',
      explain: 'Award each rubric point independently; a clear labelled drawing can earn the content points as well as the drawing point.' }
  ]);
})();
