/* L04 question bank (golden slice — copy this pattern). Owner: Lead.
   pool 'A' = Mock Form A, 'diag' = diagnostic, no pool = general (quick checks, practice, flashcards).
   Vary the MCQ answer position; every item has explain + ref; false TF items carry a fix. */
(function () {
  'use strict';
  var T = 'l04';
  KIT.bank.add([
    /* ----- Form A: MCQ (5) ----- */
    { id: 'l04.q001', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L04 p8',
      q: 'Which digital-to-analog scheme varies <b>only the amplitude</b> of the carrier?',
      choices: ['FSK', 'ASK', 'PSK', 'QAM'], answer: 1,
      explain: 'ASK changes the amplitude; FSK changes frequency, PSK changes phase, and QAM changes amplitude and phase together.' },
    { id: 'l04.q002', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L04 p5',
      q: 'An analog signal carries 3 bits per signal element at 2000 baud. What is the bit rate?',
      choices: ['667 bps', '2000 bps', '6000 bps', '8000 bps'], answer: 2,
      explain: 'S = N × 1/r, so N = S × r = 2000 × 3 = 6000 bps.' },
    { id: 'l04.q003', topic: T, pool: 'A', type: 'mcq', diff: 2, ref: 'L04 p12',
      q: 'Binary ASK with d = 1 must fit in an available bandwidth of 40 kHz. What is the maximum bit rate?',
      choices: ['20 kbps', '10 kbps', '40 kbps', '80 kbps'], answer: 0,
      explain: 'B = (1 + d) × S → 40 kHz = 2S → S = 20 kbaud. Binary ASK has r = 1, so N = 20 kbps.' },
    { id: 'l04.q004', topic: T, pool: 'A', type: 'mcq', diff: 1, ref: 'L04 p21',
      q: 'Why is PSK more robust than ASK?',
      choices: ['PSK uses a higher carrier frequency', 'PSK needs no carrier', 'PSK has a lower baud rate', 'Noise mostly alters amplitude, and PSK keeps the amplitude constant'],
      answer: 3, explain: 'The slide: “PSK is much more robust than ASK as it is not that vulnerable to noise, which changes amplitude.”' },
    { id: 'l04.q005', topic: T, pool: 'A', type: 'mcq', diff: 2, ref: 'L04 p29',
      q: 'Using the slides’ QPSK mapping (first bit → I carrier), which dibit is sent at phase <b>135°</b>?',
      choices: ['00', '11', '01', '10'], answer: 2,
      explain: '135° is the upper-left point: I negative (first bit 0), Q positive (second bit 1) → 01.' },

    /* ----- Form A: Identification (3) ----- */
    { id: 'l04.q006', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L04 p30',
      q: 'The digital-to-analog scheme that changes both the amplitude and the phase of the carrier.',
      answer: 'QAM', accept: ['quadrature amplitude modulation'],
      explain: 'QAM is a combination of ASK and PSK.' },
    { id: 'l04.q007', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L04 p8; L04 p10',
      q: 'The form of binary ASK in which a 1 sends the carrier and a 0 sends no signal at all.',
      answer: 'On-off keying', accept: ['OOK', 'on off keying', 'binary ASK', 'BASK'],
      explain: 'Binary ASK where the amplitude for one bit value is zero is called on-off keying (OOK).' },
    { id: 'l04.q008', topic: T, pool: 'A', type: 'id', diff: 1, ref: 'L04 p27; L04 p28',
      q: 'The diagram that shows each signal element as a point whose distance from the origin is its amplitude and whose angle is its phase.',
      answer: 'Constellation diagram', accept: ['constellation'],
      explain: 'A constellation diagram uses the in-phase carrier as the x-axis and the quadrature carrier as the y-axis.' },

    /* ----- Form B: MCQ (5) + Identification (3) + Essay (1) ----- */
    { id: 'l04.q023', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L04 p14',
      q: 'In binary FSK, bit 1 is sent at which frequency?',
      choices: ['f<sub>c</sub> − Δf', 'f<sub>c</sub>', 'f<sub>c</sub> + Δf', '2f<sub>c</sub>'], answer: 2,
      explain: 'Slide 14: “1” → f<sub>1</sub> = f<sub>c</sub> + Δf; “0” → f<sub>2</sub> = f<sub>c</sub> − Δf.' },
    { id: 'l04.q024', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L04 p26',
      q: 'A 16-QAM signal carries 20 Mbps with d = 0. What bandwidth does it need?',
      choices: ['20 MHz', '10 MHz', '5 MHz', '80 MHz'], answer: 2,
      explain: '16-QAM: r = log₂16 = 4 bits per element → S = 20/4 = 5 Mbaud → B = (1 + 0) × 5 MHz = 5 MHz.' },
    { id: 'l04.q025', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L04 p13',
      q: 'A band from 600 kHz to 700 kHz is shared for full-duplex ASK. Where are the two carriers?',
      choices: ['625 kHz and 675 kHz', '600 kHz and 700 kHz', '650 kHz for both', '612.5 kHz and 687.5 kHz'], answer: 0,
      explain: 'Split the band into 600–650 and 650–700 kHz; each carrier sits in the middle of its half: 625 and 675 kHz.' },
    { id: 'l04.q026', topic: T, pool: 'B', type: 'mcq', diff: 1, ref: 'L04 p27',
      q: 'On a constellation diagram, the horizontal (x) axis represents:',
      choices: ['time', 'the quadrature carrier', 'frequency', 'the in-phase carrier'], answer: 3,
      explain: 'x = in-phase (I) carrier, y = quadrature (Q) carrier.' },
    { id: 'l04.q027', topic: T, pool: 'B', type: 'mcq', diff: 2, ref: 'L04 p7',
      q: 'To carry 5 bits per signal element, how many distinct signal elements are needed?',
      choices: ['5', '10', '25', '32'], answer: 3,
      explain: 'L = 2<sup>r</sup> = 2<sup>5</sup> = 32.' },
    { id: 'l04.q028', topic: T, pool: 'B', type: 'id', diff: 1, ref: 'L04 p21',
      q: 'The digital-to-analog scheme that varies only the phase of the carrier and is much more robust than ASK.',
      answer: 'PSK', accept: ['phase shift keying'],
      explain: 'PSK keeps amplitude and frequency constant; noise mostly affects amplitude.' },
    { id: 'l04.q029', topic: T, pool: 'B', type: 'id', diff: 2, ref: 'L04 p17',
      q: 'The kind of FSK that switches frequency without adhering to the current phase of the signal.',
      answer: 'Non-coherent FSK', accept: ['noncoherent FSK', 'non coherent FSK', 'non-coherent', 'noncoherent'],
      explain: 'Non-coherent FSK can jump in phase at the switch; coherent FSK switches only at the same phase.' },
    { id: 'l04.q030', topic: T, type: 'id', diff: 1, ref: 'L04 p2',
      q: 'The analog signal of frequency f<sub>c</sub> that is modified to transport digital data.',
      answer: 'Carrier signal', accept: ['carrier', 'carrier wave'],
      explain: 'The carrier\'s amplitude, frequency or phase is manipulated to identify the data.' },
    { id: 'l04.e001', topic: T, pool: 'B', type: 'essay', diff: 2, ref: 'L04 pp8-26',
      q: 'Compare ASK, FSK and PSK: what each changes in the carrier and how each one\'s bandwidth depends on the baud rate; then say how robust ASK and PSK are to noise. ' +
        'Then explain how QPSK sends twice the bits of BPSK without needing more bandwidth. Sketches of the three signals for a short bit string are welcome.',
      rubric: [
        { pts: 1, point: 'States what each scheme varies: ASK amplitude, FSK frequency, PSK phase.' },
        { pts: 1, point: 'Bandwidths: ASK/PSK B = (1 + d)S; FSK B = (1 + d)S + 2Δf (extra spacing).' },
        { pts: 1, point: 'Noise: ASK is more vulnerable (noise changes amplitude); PSK is much more robust than ASK.' },
        { pts: 2, point: 'QPSK: 2 bits per element on I and Q carriers 90° apart → same baud rate (same bandwidth), double bit rate (N = r × S).' }
      ],
      model: '<figure data-fig="l04.modwaves" data-bits="1011" data-schemes="ook,bfsk,bpsk"></figure>' +
        '<p><b>ASK</b> changes the carrier\'s amplitude (OOK: 1 = carrier, 0 = none), <b>FSK</b> its frequency (bit 1 → f<sub>c</sub> + Δf, bit 0 → f<sub>c</sub> − Δf), and <b>PSK</b> its phase (BPSK: 0° and 180°).</p>' +
        '<p>Bandwidth follows the baud rate S: ASK and PSK need B = (1 + d)S, while FSK needs extra room for the two carriers, B = (1 + d)S + 2Δf.</p>' +
        '<p>Noise mostly disturbs amplitude, so ASK is more vulnerable; PSK keeps a constant amplitude and is much more robust than ASK.</p>' +
        '<p><b>QPSK</b> splits the bits into pairs: the first bit drives the in-phase carrier, the second the quadrature carrier (90° apart), and the sum gives one of four phases. Each element carries r = 2 bits, so at the same baud rate — and therefore the same bandwidth — it carries twice the bit rate of BPSK (N = r × S).</p>' },

    /* ----- Diagnostic (4) ----- */
    { id: 'l04.q009', topic: T, pool: 'diag', type: 'num', diff: 2, ref: 'L04 p26',
      q: 'A QPSK signal carries 8 Mbps with d = 0. What bandwidth does it need?',
      num: { value: 4e6, tol: 0.01, rel: true, unit: 'Hz' },
      explain: 'QPSK has r = 2, so S = 8 Mbps / 2 = 4 Mbaud, and B = (1 + 0) × S = 4 MHz.' },
    { id: 'l04.q010', topic: T, pool: 'diag', type: 'mcq', diff: 2, ref: 'L04 p16',
      q: 'Binary FSK in a 100 kHz band with d = 1 and 2Δf = 50 kHz gives what bit rate?',
      choices: ['50 kbps', '25 kbps', '100 kbps', '75 kbps'], answer: 1,
      explain: 'B = (1 + d)S + 2Δf → 100 = 2S + 50 → S = 25 kbaud; binary FSK has r = 1, so N = 25 kbps.' },
    { id: 'l04.q011', topic: T, pool: 'diag', type: 'id', diff: 1, ref: 'L04 p24; L04 p27',
      q: 'In QPSK, the name of the carrier that is shifted 90° from the in-phase carrier.',
      answer: 'Quadrature carrier', accept: ['quadrature', 'Q carrier', 'Q', 'quadrature (Q) carrier'],
      explain: 'QPSK uses an in-phase (I) carrier and a quadrature (Q) carrier, 90° apart.' },
    { id: 'l04.q012', topic: T, pool: 'diag', type: 'num', diff: 2, ref: 'L04 p7',
      q: 'A signal has a bit rate of 6000 bps and a baud rate of 2000 baud. How many signal levels L are needed?',
      num: { value: 8, tol: 0, rel: false, unit: '' },
      explain: 'r = N/S = 3 bits per element, so L = 2³ = 8.' },

    /* ----- General: quick checks, practice, flashcards ----- */
    { id: 'l04.q013', topic: T, type: 'mcq', diff: 1, ref: 'L04 p11; L04 p23',
      q: 'Binary ASK is implemented by multiplying the carrier by which signal?',
      choices: ['Polar NRZ', 'Unipolar NRZ', 'Manchester', 'AMI'], answer: 1,
      explain: 'BASK = unipolar NRZ × carrier (a 0 gives zero amplitude). BPSK uses polar NRZ instead.' },
    { id: 'l04.q014', topic: T, type: 'tf', diff: 1, ref: 'L04 p5',
      q: 'In analog transmission of digital data, the baud rate is greater than the bit rate.',
      answer: false, fix: 'The baud rate is less than or equal to the bit rate (S = N/r with r ≥ 1).',
      explain: 'Each signal element carries at least one bit, so there are never more elements than bits.' },
    { id: 'l04.q015', topic: T, type: 'mcq', diff: 2, ref: 'L04 p19',
      q: 'MFSK sends 2 bits per element at 2 Mbps with d = 0 and the minimum carrier spacing. What bandwidth is needed?',
      choices: ['1 MHz', '2 MHz', '4 MHz', '8 MHz'], answer: 2,
      explain: 'L = 2² = 4 frequencies, S = 2 Mbps / 2 = 1 Mbaud, B = L × S = 4 MHz.' },
    { id: 'l04.q016', topic: T, type: 'id', diff: 2, ref: 'L04 p17',
      q: 'The kind of FSK in which the switch from one frequency to the other happens only at the same phase of the signal.',
      answer: 'Coherent FSK', accept: ['coherent'],
      explain: 'Coherent FSK keeps phase continuity; non-coherent FSK switches without regard to the current phase.' },
    { id: 'l04.q017', topic: T, type: 'num', diff: 1, ref: 'L04 p12',
      q: 'An available band runs from 1.2 MHz to 1.3 MHz. Where should the carrier frequency be placed?',
      num: { value: 1.25e6, tol: 0.001, rel: true, unit: 'Hz' },
      explain: 'Put the carrier in the middle of the band: (1.2 + 1.3)/2 = 1.25 MHz.' },
    { id: 'l04.q018', topic: T, type: 'tf', diff: 1, ref: 'L04 p24',
      q: 'QPSK carries two bits per signal element using two carriers that are 90° apart.',
      answer: true, explain: 'The first bit of each pair modulates the in-phase carrier and the second the quadrature carrier.' },
    { id: 'l04.q019', topic: T, type: 'mcq', diff: 2, ref: 'L04 p30; L04 p7',
      q: 'Which statement about 16-QAM is true?',
      choices: ['It carries 16 bits per signal element', 'It carries 4 bits per signal element', 'It varies only the phase', 'It needs 16 carrier frequencies'],
      answer: 1, explain: 'L = 16 signal elements → r = log₂16 = 4 bits each. QAM varies amplitude and phase on one carrier frequency (I and Q).' },
    { id: 'l04.q020', topic: T, type: 'multi', diff: 2, ref: 'L04 p9; L04 p21',
      q: 'Select <b>all</b> schemes whose bandwidth is B = (1 + d) × S.',
      choices: ['ASK', 'Binary FSK', 'PSK', 'MFSK'], answer: [0, 2],
      explain: 'ASK and PSK both use B = (1 + d)S. FSK adds the carrier spacing (2Δf), and MFSK adds (L − 1) × 2Δf.' },
    { id: 'l04.q021', topic: T, type: 'mcq', diff: 1, ref: 'L04 p22',
      q: 'In BPSK, the signal elements for bit 1 and bit 0 differ in phase by:',
      choices: ['45°', '90°', '180°', '270°'], answer: 2,
      explain: 'BPSK uses two phases 180° apart: bit 1 → 0°, bit 0 → 180°.' },
    { id: 'l04.q022', topic: T, pool: 'B', type: 'id', diff: 2, ref: 'L04 p18',
      q: 'The device in an FSK transmitter whose output frequency follows its input voltage.',
      answer: 'Voltage-controlled oscillator', accept: ['VCO', 'voltage controlled oscillator'],
      explain: 'A VCO turns the NRZ input into a frequency change, which is binary FSK.' },
    { id: 'l04.e002', topic: T, type: 'essay', diff: 2, ref: 'L04 pp24-31',
      q: 'Draw the <b>QPSK</b> constellation with the slides’ bit labels and explain what a constellation diagram shows. Then explain how <b>16-QAM</b> carries more bits per signal element.',
      rubric: [
        { pts: 1, point: 'Axes: in-phase (I) horizontal, quadrature (Q) vertical; each point is one signal element.' },
        { pts: 1, point: 'Distance from the origin = amplitude; angle = phase.' },
        { pts: 1, point: 'QPSK: four points of equal amplitude at 45°, 135°, −135° and −45°, labelled 11, 01, 00, 10 (the first bit gives the I sign, the second the Q sign).' },
        { pts: 1, point: 'QPSK carries r = 2 bits per element (L = 4), so S = N/2.' },
        { pts: 1, point: '16-QAM changes both amplitude and phase: 16 points, r = 4 bits per element, so S = N/4 — more bits per element at the same baud rate.' }],
      model: '<p>A constellation diagram plots each signal element as a point: the in-phase carrier on the horizontal axis and the quadrature carrier on the vertical axis. The point\'s distance from the origin is the amplitude and its angle is the phase. <span class="chip ref">L04 p27</span> <span class="chip ref">L04 p28</span></p>' +
        '<figure data-fig="l04.constellation" data-scheme="qpsk"></figure>' +
        '<p>QPSK sends two bits per element: the first bit sets the I sign and the second the Q sign, giving four equal-amplitude points — 11 at 45°, 01 at 135°, 00 at −135°, 10 at −45°. With r = 2, S = N/2. <span class="chip ref">L04 p25</span> <span class="chip ref">L04 p29</span></p>' +
        '<p><b>16-QAM</b> combines ASK and PSK: points differ in amplitude and phase, so there are 16 of them and each carries r = 4 bits — S = N/4. <span class="chip ref">L04 p30</span> <span class="chip ref">L04 p31</span></p>' +
        '<figure data-fig="l04.constellation" data-scheme="16qam"></figure>',
      explain: 'Award each rubric point independently; the drawing can earn the first three points.' }
  ]);
})();
